package com.helger.ubl22.codelist;

import com.helger.commons.annotation.CodingStyleguideUnaware;
import com.helger.commons.annotation.Nonempty;
import com.helger.commons.id.IHasID;
import com.helger.commons.lang.EnumHelper;
import com.helger.commons.name.IHasDisplayName;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;


/**
 * This file was automatically generated from Genericode file CountryIdentificationCode-2.2.gc. Do NOT edit!
 * It contains a total of 498 entries!
 * @author com.helger.ubl22.main.MainCreateEnumsGenericode22
 */
@CodingStyleguideUnaware
public enum ECountryIdentificationCode22
    implements IHasID<String> , IHasDisplayName
{
    AF("AF", "Afghanistan", "004", "Afghanistan (l')", "AFG"),
    AX("AX", "\u00c5land Islands", "248", "\u00c5land(les \u00celes)", "ALA"),
    AL("AL", "Albania", "008", "Albanie (l')", "ALB"),
    DZ("DZ", "Algeria", "012", "Alg\u00e9rie (l')", "DZA"),
    AS("AS", "American Samoa", "016", "Samoa am\u00e9ricaines (les)", "ASM"),
    AD("AD", "Andorra", "020", "Andorre (l')", "AND"),
    AO("AO", "Angola", "024", "Angola (l')", "AGO"),
    AI("AI", "Anguilla", "660", "Anguilla", "AIA"),
    AQ("AQ", "Antarctica", "010", "Antarctique (l')", "ATA"),
    AG("AG", "Antigua and Barbuda", "028", "Antigua-et-Barbuda", "ATG"),
    AR("AR", "Argentina", "032", "Argentine (l')", "ARG"),
    AM("AM", "Armenia", "051", "Arm\u00e9nie (l')", "ARM"),
    AW("AW", "Aruba", "533", "Aruba", "ABW"),
    AU("AU", "Australia", "036", "Australie (l')", "AUS"),
    AT("AT", "Austria", "040", "Autriche (l')", "AUT"),
    AZ("AZ", "Azerbaijan", "031", "Azerba\u00efdjan (l')", "AZE"),
    BS("BS", "Bahamas (the)", "044", "Bahamas (les)", "BHS"),
    BH("BH", "Bahrain", "048", "Bahre\u00efn", "BHR"),
    BD("BD", "Bangladesh", "050", "Bangladesh (le)", "BGD"),
    BB("BB", "Barbados", "052", "Barbade (la)", "BRB"),
    BY("BY", "Belarus", "112", "B\u00e9larus (le)", "BLR"),
    BE("BE", "Belgium", "056", "Belgique (la)", "BEL"),
    BZ("BZ", "Belize", "084", "Belize (le)", "BLZ"),
    BJ("BJ", "Benin", "204", "B\u00e9nin (le)", "BEN"),
    BM("BM", "Bermuda", "060", "Bermudes (les)", "BMU"),
    BT("BT", "Bhutan", "064", "Bhoutan (le)", "BTN"),
    BO("BO", "Bolivia (Plurinational State of)", "068", "Bolivie (\u00c9tat plurinational de)", "BOL"),
    BQ("BQ", "Bonaire, Sint Eustatius and Saba", "535", "Bonaire, Saint-Eustache et Saba", "BES"),
    BA("BA", "Bosnia and Herzegovina", "070", "Bosnie-Herz\u00e9govine (la)", "BIH"),
    BW("BW", "Botswana", "072", "Botswana (le)", "BWA"),
    BV("BV", "Bouvet Island", "074", "Bouvet (l'\u00cele)", "BVT"),
    BR("BR", "Brazil", "076", "Br\u00e9sil (le)", "BRA"),
    IO("IO", "British Indian Ocean Territory (the)", "086", "Indien (le\u00a0Territoire britannique de l'oc\u00e9an)", "IOT"),
    BN("BN", "Brunei Darussalam", "096", "Brun\u00e9i Darussalam (le)", "BRN"),
    BG("BG", "Bulgaria", "100", "Bulgarie (la)", "BGR"),
    BF("BF", "Burkina Faso", "854", "Burkina Faso (le)", "BFA"),
    BI("BI", "Burundi", "108", "Burundi (le)", "BDI"),
    CV("CV", "Cabo Verde", "132", "Cabo Verde", "CPV"),
    KH("KH", "Cambodia", "116", "Cambodge (le)", "KHM"),
    CM("CM", "Cameroon", "120", "Cameroun (le)", "CMR"),
    CA("CA", "Canada", "124", "Canada (le)", "CAN"),
    KY("KY", "Cayman Islands (the)", "136", "Ca\u00efmans (les\u00a0\u00celes)", "CYM"),
    CF("CF", "Central African Republic (the)", "140", "R\u00e9publique centrafricaine (la)", "CAF"),
    TD("TD", "Chad", "148", "Tchad (le)", "TCD"),
    CL("CL", "Chile", "152", "Chili (le)", "CHL"),
    CN("CN", "China", "156", "Chine (la)", "CHN"),
    CX("CX", "Christmas Island", "162", "Christmas (l'\u00cele)", "CXR"),
    CC("CC", "Cocos (Keeling) Islands (the)", "166", "Cocos (les\u00a0\u00celes)/ Keeling (les\u00a0\u00celes)", "CCK"),
    CO("CO", "Colombia", "170", "Colombie (la)", "COL"),
    KM("KM", "Comoros (the)", "174", "Comores (les)", "COM"),
    CD("CD", "Congo (the Democratic Republic of the)", "180", "Congo (la R\u00e9publique d\u00e9mocratique du)", "COD"),
    CG("CG", "Congo (the)", "178", "Congo (le)", "COG"),
    CK("CK", "Cook Islands (the)", "184", "Cook (les \u00celes)", "COK"),
    CR("CR", "Costa Rica", "188", "Costa Rica (le)", "CRI"),
    CI("CI", "C\u00f4te d'Ivoire", "384", "C\u00f4te d'Ivoire (la)", "CIV"),
    HR("HR", "Croatia", "191", "Croatie (la)", "HRV"),
    CU("CU", "Cuba", "192", "Cuba", "CUB"),
    CW("CW", "Cura\u00e7ao", "531", "Cura\u00e7ao", "CUW"),
    CY("CY", "Cyprus", "196", "Chypre", "CYP"),
    CZ("CZ", "Czechia", "203", "Tch\u00e9quie (la)", "CZE"),
    DK("DK", "Denmark", "208", "Danemark (le)", "DNK"),
    DJ("DJ", "Djibouti", "262", "Djibouti", "DJI"),
    DM("DM", "Dominica", "212", "Dominique (la)", "DMA"),
    DO("DO", "Dominican Republic (the)", "214", "dominicaine (la\u00a0R\u00e9publique)", "DOM"),
    EC("EC", "Ecuador", "218", "\u00c9quateur (l')", "ECU"),
    EG("EG", "Egypt", "818", "\u00c9gypte (l')", "EGY"),
    SV("SV", "El Salvador", "222", "El Salvador", "SLV"),
    GQ("GQ", "Equatorial Guinea", "226", "Guin\u00e9e \u00e9quatoriale (la)", "GNQ"),
    ER("ER", "Eritrea", "232", "\u00c9rythr\u00e9e (l')", "ERI"),
    EE("EE", "Estonia", "233", "Estonie (l')", "EST"),
    ET("ET", "Ethiopia", "231", "\u00c9thiopie (l')", "ETH"),
    FK("FK", "Falkland Islands (the) [Malvinas]", "238", "Falkland (les \u00celes)/Malouines (les \u00celes)", "FLK"),
    FO("FO", "Faroe Islands (the)", "234", "F\u00e9ro\u00e9 (les \u00celes)", "FRO"),
    FJ("FJ", "Fiji", "242", "Fidji (les)", "FJI"),
    FI("FI", "Finland", "246", "Finlande (la)", "FIN"),
    FR("FR", "France", "250", "France (la)", "FRA"),
    GF("GF", "French Guiana", "254", "Guyane fran\u00e7aise (la\u00a0)", "GUF"),
    PF("PF", "French Polynesia", "258", "Polyn\u00e9sie fran\u00e7aise (la)", "PYF"),
    TF("TF", "French Southern Territories (the)", "260", "Terres australes fran\u00e7aises (les)", "ATF"),
    GA("GA", "Gabon", "266", "Gabon (le)", "GAB"),
    GM("GM", "Gambia (the)", "270", "Gambie (la)", "GMB"),
    GE("GE", "Georgia", "268", "G\u00e9orgie (la)", "GEO"),
    DE("DE", "Germany", "276", "Allemagne (l')", "DEU"),
    GH("GH", "Ghana", "288", "Ghana (le)", "GHA"),
    GI("GI", "Gibraltar", "292", "Gibraltar", "GIB"),
    GR("GR", "Greece", "300", "Gr\u00e8ce (la)", "GRC"),
    GL("GL", "Greenland", "304", "Groenland (le)", "GRL"),
    GD("GD", "Grenada", "308", "Grenade (la)", "GRD"),
    GP("GP", "Guadeloupe", "312", "Guadeloupe (la)", "GLP"),
    GU("GU", "Guam", "316", "Guam", "GUM"),
    GT("GT", "Guatemala", "320", "Guatemala (le)", "GTM"),
    GG("GG", "Guernsey", "831", "Guernesey", "GGY"),
    GN("GN", "Guinea", "324", "Guin\u00e9e (la)", "GIN"),
    GW("GW", "Guinea-Bissau", "624", "Guin\u00e9e-Bissau (la)", "GNB"),
    GY("GY", "Guyana", "328", "Guyana (le)", "GUY"),
    HT("HT", "Haiti", "332", "Ha\u00efti", "HTI"),
    HM("HM", "Heard Island and McDonald Islands", "334", "Heard-et-\u00celes MacDonald (l'\u00cele)", "HMD"),
    VA("VA", "Holy See (the)", "336", "Saint-Si\u00e8ge (le)", "VAT"),
    HN("HN", "Honduras", "340", "Honduras (le)", "HND"),
    HK("HK", "Hong Kong", "344", "Hong Kong", "HKG"),
    HU("HU", "Hungary", "348", "Hongrie (la)", "HUN"),
    IS("IS", "Iceland", "352", "Islande (l')", "ISL"),
    IN("IN", "India", "356", "Inde (l')", "IND"),
    ID("ID", "Indonesia", "360", "Indon\u00e9sie (l')", "IDN"),
    IR("IR", "Iran (Islamic Republic of)", "364", "Iran (R\u00e9publique Islamique d')", "IRN"),
    IQ("IQ", "Iraq", "368", "Iraq (l')", "IRQ"),
    IE("IE", "Ireland", "372", "Irlande (l')", "IRL"),
    IM("IM", "Isle of Man", "833", "\u00cele de Man", "IMN"),
    IL("IL", "Israel", "376", "Isra\u00ebl", "ISR"),
    IT("IT", "Italy", "380", "Italie (l')", "ITA"),
    JM("JM", "Jamaica", "388", "Jama\u00efque (la)", "JAM"),
    JP("JP", "Japan", "392", "Japon (le)", "JPN"),
    JE("JE", "Jersey", "832", "Jersey", "JEY"),
    JO("JO", "Jordan", "400", "Jordanie (la)", "JOR"),
    KZ("KZ", "Kazakhstan", "398", "Kazakhstan (le)", "KAZ"),
    KE("KE", "Kenya", "404", "Kenya (le)", "KEN"),
    KI("KI", "Kiribati", "296", "Kiribati", "KIR"),
    KP("KP", "Korea (the Democratic People's Republic of)", "408", "Cor\u00e9e (la\u00a0R\u00e9publique populaire d\u00e9mocratique de)", "PRK"),
    KR("KR", "Korea (the Republic of)", "410", "Cor\u00e9e (la R\u00e9publique de)", "KOR"),
    KW("KW", "Kuwait", "414", "Kowe\u00eft (le)", "KWT"),
    KG("KG", "Kyrgyzstan", "417", "Kirghizistan (le)", "KGZ"),
    LA("LA", "Lao People's Democratic Republic (the)", "418", "Lao, R\u00e9publique d\u00e9mocratique populaire", "LAO"),
    LV("LV", "Latvia", "428", "Lettonie (la)", "LVA"),
    LB("LB", "Lebanon", "422", "Liban (le)", "LBN"),
    LS("LS", "Lesotho", "426", "Lesotho (le)", "LSO"),
    LR("LR", "Liberia", "430", "Lib\u00e9ria (le)", "LBR"),
    LY("LY", "Libya", "434", "Libye (la)", "LBY"),
    LI("LI", "Liechtenstein", "438", "Liechtenstein (le)", "LIE"),
    LT("LT", "Lithuania", "440", "Lituanie (la)", "LTU"),
    LU("LU", "Luxembourg", "442", "Luxembourg (le)", "LUX"),
    MO("MO", "Macao", "446", "Macao", "MAC"),
    MK("MK", "Macedonia (the former Yugoslav Republic of)", "807", "Mac\u00e9doine (l'ex\u2011R\u00e9publique yougoslave de)", "MKD"),
    MG("MG", "Madagascar", "450", "Madagascar", "MDG"),
    MW("MW", "Malawi", "454", "Malawi (le)", "MWI"),
    MY("MY", "Malaysia", "458", "Malaisie (la)", "MYS"),
    MV("MV", "Maldives", "462", "Maldives (les)", "MDV"),
    ML("ML", "Mali", "466", "Mali (le)", "MLI"),
    MT("MT", "Malta", "470", "Malte", "MLT"),
    MH("MH", "Marshall Islands (the)", "584", "Marshall (\u00celes)", "MHL"),
    MQ("MQ", "Martinique", "474", "Martinique (la)", "MTQ"),
    MR("MR", "Mauritania", "478", "Mauritanie (la)", "MRT"),
    MU("MU", "Mauritius", "480", "Maurice", "MUS"),
    YT("YT", "Mayotte", "175", "Mayotte", "MYT"),
    MX("MX", "Mexico", "484", "Mexique (le)", "MEX"),
    FM("FM", "Micronesia (Federated States of)", "583", "Micron\u00e9sie (\u00c9tats f\u00e9d\u00e9r\u00e9s de)", "FSM"),
    MD("MD", "Moldova (the Republic of)", "498", "Moldova, R\u00e9publique de", "MDA"),
    MC("MC", "Monaco", "492", "Monaco", "MCO"),
    MN("MN", "Mongolia", "496", "Mongolie (la)", "MNG"),
    ME("ME", "Montenegro", "499", "Mont\u00e9n\u00e9gro (le)", "MNE"),
    MS("MS", "Montserrat", "500", "Montserrat", "MSR"),
    MA("MA", "Morocco", "504", "Maroc (le)", "MAR"),
    MZ("MZ", "Mozambique", "508", "Mozambique (le)", "MOZ"),
    MM("MM", "Myanmar", "104", "Myanmar (le)", "MMR"),
    NA("NA", "Namibia", "516", "Namibie (la)", "NAM"),
    NR("NR", "Nauru", "520", "Nauru", "NRU"),
    NP("NP", "Nepal", "524", "N\u00e9pal (le)", "NPL"),
    NL("NL", "Netherlands (the)", "528", "Pays-Bas (les)", "NLD"),
    NC("NC", "New Caledonia", "540", "Nouvelle-Cal\u00e9donie (la)", "NCL"),
    NZ("NZ", "New Zealand", "554", "Nouvelle-Z\u00e9lande (la)", "NZL"),
    NI("NI", "Nicaragua", "558", "Nicaragua (le)", "NIC"),
    NE("NE", "Niger (the)", "562", "Niger (le)", "NER"),
    NG("NG", "Nigeria", "566", "Nig\u00e9ria (le)", "NGA"),
    NU("NU", "Niue", "570", "Niue", "NIU"),
    NF("NF", "Norfolk Island", "574", "Norfolk (l'\u00cele)", "NFK"),
    MP("MP", "Northern Mariana Islands (the)", "580", "Mariannes du Nord (les \u00celes)", "MNP"),
    NO("NO", "Norway", "578", "Norv\u00e8ge (la)", "NOR"),
    OM("OM", "Oman", "512", "Oman", "OMN"),
    PK("PK", "Pakistan", "586", "Pakistan (le)", "PAK"),
    PW("PW", "Palau", "585", "Palaos (les)", "PLW"),
    PS("PS", "Palestine, State of", "275", "Palestine, \u00c9tat de", "PSE"),
    PA("PA", "Panama", "591", "Panama (le)", "PAN"),
    PG("PG", "Papua New Guinea", "598", "Papouasie-Nouvelle-Guin\u00e9e (la)", "PNG"),
    PY("PY", "Paraguay", "600", "Paraguay (le)", "PRY"),
    PE("PE", "Peru", "604", "P\u00e9rou (le)", "PER"),
    PH("PH", "Philippines (the)", "608", "Philippines (les)", "PHL"),
    PN("PN", "Pitcairn", "612", "Pitcairn", "PCN"),
    PL("PL", "Poland", "616", "Pologne (la)", "POL"),
    PT("PT", "Portugal", "620", "Portugal (le)", "PRT"),
    PR("PR", "Puerto Rico", "630", "Porto Rico", "PRI"),
    QA("QA", "Qatar", "634", "Qatar (le)", "QAT"),
    RE("RE", "R\u00e9union", "638", "R\u00e9union (La)", "REU"),
    RO("RO", "Romania", "642", "Roumanie (la)", "ROU"),
    RU("RU", "Russian Federation (the)", "643", "Russie (la F\u00e9d\u00e9ration de)", "RUS"),
    RW("RW", "Rwanda", "646", "Rwanda (le)", "RWA"),
    BL("BL", "Saint Barth\u00e9lemy", "652", "Saint-Barth\u00e9lemy", "BLM"),
    SH("SH", "Saint Helena, Ascension and Tristan da Cunha", "654", "Sainte-H\u00e9l\u00e8ne, Ascension et Tristan da Cunha", "SHN"),
    KN("KN", "Saint Kitts and Nevis", "659", "Saint-Kitts-et-Nevis", "KNA"),
    LC("LC", "Saint Lucia", "662", "Sainte-Lucie", "LCA"),
    MF("MF", "Saint Martin (French part)", "663", "Saint-Martin (partie fran\u00e7aise)", "MAF"),
    PM("PM", "Saint Pierre and Miquelon", "666", "Saint-Pierre-et-Miquelon", "SPM"),
    VC("VC", "Saint Vincent and the Grenadines", "670", "Saint-Vincent-et-les Grenadines", "VCT"),
    WS("WS", "Samoa", "882", "Samoa (le)", "WSM"),
    SM("SM", "San Marino", "674", "Saint-Marin", "SMR"),
    ST("ST", "Sao Tome and Principe", "678", "Sao Tom\u00e9-et-Principe", "STP"),
    SA("SA", "Saudi Arabia", "682", "Arabie saoudite (l')", "SAU"),
    SN("SN", "Senegal", "686", "S\u00e9n\u00e9gal (le)", "SEN"),
    RS("RS", "Serbia", "688", "Serbie (la)", "SRB"),
    SC("SC", "Seychelles", "690", "Seychelles (les)", "SYC"),
    SL("SL", "Sierra Leone", "694", "Sierra Leone (la)", "SLE"),
    SG("SG", "Singapore", "702", "Singapour", "SGP"),
    SX("SX", "Sint Maarten (Dutch part)", "534", "Saint-Martin (partie n\u00e9erlandaise)", "SXM"),
    SK("SK", "Slovakia", "703", "Slovaquie (la)", "SVK"),
    SI("SI", "Slovenia", "705", "Slov\u00e9nie (la)", "SVN"),
    SB("SB", "Solomon Islands", "090", "Salomon (\u00celes)", "SLB"),
    SO("SO", "Somalia", "706", "Somalie (la)", "SOM"),
    ZA("ZA", "South Africa", "710", "Afrique du Sud (l')", "ZAF"),
    GS("GS", "South Georgia and the South Sandwich Islands", "239", "G\u00e9orgie du Sud-et-les \u00celes Sandwich du Sud (la)", "SGS"),
    SS("SS", "South Sudan", "728", "Soudan du Sud (le)", "SSD"),
    ES("ES", "Spain", "724", "Espagne (l')", "ESP"),
    LK("LK", "Sri Lanka", "144", "Sri Lanka", "LKA"),
    SD("SD", "Sudan (the)", "729", "Soudan (le)", "SDN"),
    SR("SR", "Suriname", "740", "Suriname (le)", "SUR"),
    SJ("SJ", "Svalbard and Jan Mayen", "744", "Svalbard et l'\u00cele Jan Mayen (le)", "SJM"),
    SZ("SZ", "Swaziland", "748", "Swaziland (le)", "SWZ"),
    SE("SE", "Sweden", "752", "Su\u00e8de (la)", "SWE"),
    CH("CH", "Switzerland", "756", "Suisse (la)", "CHE"),
    SY("SY", "Syrian Arab Republic", "760", "R\u00e9publique arabe syrienne (la)", "SYR"),
    TW("TW", "Taiwan (Province of China)", "158", "Ta\u00efwan (Province de Chine)", "TWN"),
    TJ("TJ", "Tajikistan", "762", "Tadjikistan (le)", "TJK"),
    TZ("TZ", "Tanzania, United Republic of", "834", "Tanzanie, R\u00e9publique-Unie de", "TZA"),
    TH("TH", "Thailand", "764", "Tha\u00eflande (la)", "THA"),
    TL("TL", "Timor-Leste", "626", "Timor-Leste (le)", "TLS"),
    TG("TG", "Togo", "768", "Togo (le)", "TGO"),
    TK("TK", "Tokelau", "772", "Tokelau (les)", "TKL"),
    TO("TO", "Tonga", "776", "Tonga (les)", "TON"),
    TT("TT", "Trinidad and Tobago", "780", "Trinit\u00e9-et-Tobago (la)", "TTO"),
    TN("TN", "Tunisia", "788", "Tunisie (la)", "TUN"),
    TR("TR", "Turkey", "792", "Turquie (la)", "TUR"),
    TM("TM", "Turkmenistan", "795", "Turkm\u00e9nistan (le)", "TKM"),
    TC("TC", "Turks and Caicos Islands (the)", "796", "Turks-et-Ca\u00efcos (les \u00celes)", "TCA"),
    TV("TV", "Tuvalu", "798", "Tuvalu (les)", "TUV"),
    UG("UG", "Uganda", "800", "Ouganda (l')", "UGA"),
    UA("UA", "Ukraine", "804", "Ukraine (l')", "UKR"),
    AE("AE", "United Arab Emirates (the)", "784", "\u00c9mirats arabes unis (les)", "ARE"),
    GB("GB", "United Kingdom of Great Britain and Northern Ireland (the)", "826", "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)", "GBR"),
    UM("UM", "United States Minor Outlying Islands (the)", "581", "\u00celes mineures \u00e9loign\u00e9es des \u00c9tats-Unis (les)", "UMI"),
    US("US", "United States of America (the)", "840", "\u00c9tats-Unis d'Am\u00e9rique (les)", "USA"),
    UY("UY", "Uruguay", "858", "Uruguay (l')", "URY"),
    UZ("UZ", "Uzbekistan", "860", "Ouzb\u00e9kistan (l')", "UZB"),
    VU("VU", "Vanuatu", "548", "Vanuatu (le)", "VUT"),
    VE("VE", "Venezuela (Bolivarian Republic of)", "862", "Venezuela (R\u00e9publique bolivarienne du)", "VEN"),
    VN("VN", "Viet Nam", "704", "Viet Nam (le)", "VNM"),
    VG("VG", "Virgin Islands (British)", "092", "Vierges britanniques (les\u00a0\u00celes)", "VGB"),
    VI("VI", "Virgin Islands (U.S.)", "850", "Vierges des \u00c9tats-Unis (les \u00celes)", "VIR"),
    WF("WF", "Wallis and Futuna", "876", "Wallis-et-Futuna\u00a0", "WLF"),
    EH("EH", "Western Sahara*", "732", "Sahara occidental (le)*", "ESH"),
    YE("YE", "Yemen", "887", "Y\u00e9men (le)", "YEM"),
    ZM("ZM", "Zambia", "894", "Zambie (la)", "ZMB"),
    ZW("ZW", "Zimbabwe", "716", "Zimbabwe (le)", "ZWE"),
    AFG("AFG", "Afghanistan", "004", "Afghanistan (l')", "AF"),
    ALA("ALA", "\u00c5land Islands", "248", "\u00c5land(les \u00celes)", "AX"),
    ALB("ALB", "Albania", "008", "Albanie (l')", "AL"),
    DZA("DZA", "Algeria", "012", "Alg\u00e9rie (l')", "DZ"),
    ASM("ASM", "American Samoa", "016", "Samoa am\u00e9ricaines (les)", "AS"),
    AND("AND", "Andorra", "020", "Andorre (l')", "AD"),
    AGO("AGO", "Angola", "024", "Angola (l')", "AO"),
    AIA("AIA", "Anguilla", "660", "Anguilla", "AI"),
    ATA("ATA", "Antarctica", "010", "Antarctique (l')", "AQ"),
    ATG("ATG", "Antigua and Barbuda", "028", "Antigua-et-Barbuda", "AG"),
    ARG("ARG", "Argentina", "032", "Argentine (l')", "AR"),
    ARM("ARM", "Armenia", "051", "Arm\u00e9nie (l')", "AM"),
    ABW("ABW", "Aruba", "533", "Aruba", "AW"),
    AUS("AUS", "Australia", "036", "Australie (l')", "AU"),
    AUT("AUT", "Austria", "040", "Autriche (l')", "AT"),
    AZE("AZE", "Azerbaijan", "031", "Azerba\u00efdjan (l')", "AZ"),
    BHS("BHS", "Bahamas (the)", "044", "Bahamas (les)", "BS"),
    BHR("BHR", "Bahrain", "048", "Bahre\u00efn", "BH"),
    BGD("BGD", "Bangladesh", "050", "Bangladesh (le)", "BD"),
    BRB("BRB", "Barbados", "052", "Barbade (la)", "BB"),
    BLR("BLR", "Belarus", "112", "B\u00e9larus (le)", "BY"),
    BEL("BEL", "Belgium", "056", "Belgique (la)", "BE"),
    BLZ("BLZ", "Belize", "084", "Belize (le)", "BZ"),
    BEN("BEN", "Benin", "204", "B\u00e9nin (le)", "BJ"),
    BMU("BMU", "Bermuda", "060", "Bermudes (les)", "BM"),
    BTN("BTN", "Bhutan", "064", "Bhoutan (le)", "BT"),
    BOL("BOL", "Bolivia (Plurinational State of)", "068", "Bolivie (\u00c9tat plurinational de)", "BO"),
    BES("BES", "Bonaire, Sint Eustatius and Saba", "535", "Bonaire, Saint-Eustache et Saba", "BQ"),
    BIH("BIH", "Bosnia and Herzegovina", "070", "Bosnie-Herz\u00e9govine (la)", "BA"),
    BWA("BWA", "Botswana", "072", "Botswana (le)", "BW"),
    BVT("BVT", "Bouvet Island", "074", "Bouvet (l'\u00cele)", "BV"),
    BRA("BRA", "Brazil", "076", "Br\u00e9sil (le)", "BR"),
    IOT("IOT", "British Indian Ocean Territory (the)", "086", "Indien (le\u00a0Territoire britannique de l'oc\u00e9an)", "IO"),
    BRN("BRN", "Brunei Darussalam", "096", "Brun\u00e9i Darussalam (le)", "BN"),
    BGR("BGR", "Bulgaria", "100", "Bulgarie (la)", "BG"),
    BFA("BFA", "Burkina Faso", "854", "Burkina Faso (le)", "BF"),
    BDI("BDI", "Burundi", "108", "Burundi (le)", "BI"),
    CPV("CPV", "Cabo Verde", "132", "Cabo Verde", "CV"),
    KHM("KHM", "Cambodia", "116", "Cambodge (le)", "KH"),
    CMR("CMR", "Cameroon", "120", "Cameroun (le)", "CM"),
    CAN("CAN", "Canada", "124", "Canada (le)", "CA"),
    CYM("CYM", "Cayman Islands (the)", "136", "Ca\u00efmans (les\u00a0\u00celes)", "KY"),
    CAF("CAF", "Central African Republic (the)", "140", "R\u00e9publique centrafricaine (la)", "CF"),
    TCD("TCD", "Chad", "148", "Tchad (le)", "TD"),
    CHL("CHL", "Chile", "152", "Chili (le)", "CL"),
    CHN("CHN", "China", "156", "Chine (la)", "CN"),
    CXR("CXR", "Christmas Island", "162", "Christmas (l'\u00cele)", "CX"),
    CCK("CCK", "Cocos (Keeling) Islands (the)", "166", "Cocos (les\u00a0\u00celes)/ Keeling (les\u00a0\u00celes)", "CC"),
    COL("COL", "Colombia", "170", "Colombie (la)", "CO"),
    COM("COM", "Comoros (the)", "174", "Comores (les)", "KM"),
    COD("COD", "Congo (the Democratic Republic of the)", "180", "Congo (la R\u00e9publique d\u00e9mocratique du)", "CD"),
    COG("COG", "Congo (the)", "178", "Congo (le)", "CG"),
    COK("COK", "Cook Islands (the)", "184", "Cook (les \u00celes)", "CK"),
    CRI("CRI", "Costa Rica", "188", "Costa Rica (le)", "CR"),
    CIV("CIV", "C\u00f4te d'Ivoire", "384", "C\u00f4te d'Ivoire (la)", "CI"),
    HRV("HRV", "Croatia", "191", "Croatie (la)", "HR"),
    CUB("CUB", "Cuba", "192", "Cuba", "CU"),
    CUW("CUW", "Cura\u00e7ao", "531", "Cura\u00e7ao", "CW"),
    CYP("CYP", "Cyprus", "196", "Chypre", "CY"),
    CZE("CZE", "Czechia", "203", "Tch\u00e9quie (la)", "CZ"),
    DNK("DNK", "Denmark", "208", "Danemark (le)", "DK"),
    DJI("DJI", "Djibouti", "262", "Djibouti", "DJ"),
    DMA("DMA", "Dominica", "212", "Dominique (la)", "DM"),
    DOM("DOM", "Dominican Republic (the)", "214", "dominicaine (la\u00a0R\u00e9publique)", "DO"),
    ECU("ECU", "Ecuador", "218", "\u00c9quateur (l')", "EC"),
    EGY("EGY", "Egypt", "818", "\u00c9gypte (l')", "EG"),
    SLV("SLV", "El Salvador", "222", "El Salvador", "SV"),
    GNQ("GNQ", "Equatorial Guinea", "226", "Guin\u00e9e \u00e9quatoriale (la)", "GQ"),
    ERI("ERI", "Eritrea", "232", "\u00c9rythr\u00e9e (l')", "ER"),
    EST("EST", "Estonia", "233", "Estonie (l')", "EE"),
    ETH("ETH", "Ethiopia", "231", "\u00c9thiopie (l')", "ET"),
    FLK("FLK", "Falkland Islands (the) [Malvinas]", "238", "Falkland (les \u00celes)/Malouines (les \u00celes)", "FK"),
    FRO("FRO", "Faroe Islands (the)", "234", "F\u00e9ro\u00e9 (les \u00celes)", "FO"),
    FJI("FJI", "Fiji", "242", "Fidji (les)", "FJ"),
    FIN("FIN", "Finland", "246", "Finlande (la)", "FI"),
    FRA("FRA", "France", "250", "France (la)", "FR"),
    GUF("GUF", "French Guiana", "254", "Guyane fran\u00e7aise (la\u00a0)", "GF"),
    PYF("PYF", "French Polynesia", "258", "Polyn\u00e9sie fran\u00e7aise (la)", "PF"),
    ATF("ATF", "French Southern Territories (the)", "260", "Terres australes fran\u00e7aises (les)", "TF"),
    GAB("GAB", "Gabon", "266", "Gabon (le)", "GA"),
    GMB("GMB", "Gambia (the)", "270", "Gambie (la)", "GM"),
    GEO("GEO", "Georgia", "268", "G\u00e9orgie (la)", "GE"),
    DEU("DEU", "Germany", "276", "Allemagne (l')", "DE"),
    GHA("GHA", "Ghana", "288", "Ghana (le)", "GH"),
    GIB("GIB", "Gibraltar", "292", "Gibraltar", "GI"),
    GRC("GRC", "Greece", "300", "Gr\u00e8ce (la)", "GR"),
    GRL("GRL", "Greenland", "304", "Groenland (le)", "GL"),
    GRD("GRD", "Grenada", "308", "Grenade (la)", "GD"),
    GLP("GLP", "Guadeloupe", "312", "Guadeloupe (la)", "GP"),
    GUM("GUM", "Guam", "316", "Guam", "GU"),
    GTM("GTM", "Guatemala", "320", "Guatemala (le)", "GT"),
    GGY("GGY", "Guernsey", "831", "Guernesey", "GG"),
    GIN("GIN", "Guinea", "324", "Guin\u00e9e (la)", "GN"),
    GNB("GNB", "Guinea-Bissau", "624", "Guin\u00e9e-Bissau (la)", "GW"),
    GUY("GUY", "Guyana", "328", "Guyana (le)", "GY"),
    HTI("HTI", "Haiti", "332", "Ha\u00efti", "HT"),
    HMD("HMD", "Heard Island and McDonald Islands", "334", "Heard-et-\u00celes MacDonald (l'\u00cele)", "HM"),
    VAT("VAT", "Holy See (the)", "336", "Saint-Si\u00e8ge (le)", "VA"),
    HND("HND", "Honduras", "340", "Honduras (le)", "HN"),
    HKG("HKG", "Hong Kong", "344", "Hong Kong", "HK"),
    HUN("HUN", "Hungary", "348", "Hongrie (la)", "HU"),
    ISL("ISL", "Iceland", "352", "Islande (l')", "IS"),
    IND("IND", "India", "356", "Inde (l')", "IN"),
    IDN("IDN", "Indonesia", "360", "Indon\u00e9sie (l')", "ID"),
    IRN("IRN", "Iran (Islamic Republic of)", "364", "Iran (R\u00e9publique Islamique d')", "IR"),
    IRQ("IRQ", "Iraq", "368", "Iraq (l')", "IQ"),
    IRL("IRL", "Ireland", "372", "Irlande (l')", "IE"),
    IMN("IMN", "Isle of Man", "833", "\u00cele de Man", "IM"),
    ISR("ISR", "Israel", "376", "Isra\u00ebl", "IL"),
    ITA("ITA", "Italy", "380", "Italie (l')", "IT"),
    JAM("JAM", "Jamaica", "388", "Jama\u00efque (la)", "JM"),
    JPN("JPN", "Japan", "392", "Japon (le)", "JP"),
    JEY("JEY", "Jersey", "832", "Jersey", "JE"),
    JOR("JOR", "Jordan", "400", "Jordanie (la)", "JO"),
    KAZ("KAZ", "Kazakhstan", "398", "Kazakhstan (le)", "KZ"),
    KEN("KEN", "Kenya", "404", "Kenya (le)", "KE"),
    KIR("KIR", "Kiribati", "296", "Kiribati", "KI"),
    PRK("PRK", "Korea (the Democratic People's Republic of)", "408", "Cor\u00e9e (la\u00a0R\u00e9publique populaire d\u00e9mocratique de)", "KP"),
    KOR("KOR", "Korea (the Republic of)", "410", "Cor\u00e9e (la R\u00e9publique de)", "KR"),
    KWT("KWT", "Kuwait", "414", "Kowe\u00eft (le)", "KW"),
    KGZ("KGZ", "Kyrgyzstan", "417", "Kirghizistan (le)", "KG"),
    LAO("LAO", "Lao People's Democratic Republic (the)", "418", "Lao, R\u00e9publique d\u00e9mocratique populaire", "LA"),
    LVA("LVA", "Latvia", "428", "Lettonie (la)", "LV"),
    LBN("LBN", "Lebanon", "422", "Liban (le)", "LB"),
    LSO("LSO", "Lesotho", "426", "Lesotho (le)", "LS"),
    LBR("LBR", "Liberia", "430", "Lib\u00e9ria (le)", "LR"),
    LBY("LBY", "Libya", "434", "Libye (la)", "LY"),
    LIE("LIE", "Liechtenstein", "438", "Liechtenstein (le)", "LI"),
    LTU("LTU", "Lithuania", "440", "Lituanie (la)", "LT"),
    LUX("LUX", "Luxembourg", "442", "Luxembourg (le)", "LU"),
    MAC("MAC", "Macao", "446", "Macao", "MO"),
    MKD("MKD", "Macedonia (the former Yugoslav Republic of)", "807", "Mac\u00e9doine (l'ex\u2011R\u00e9publique yougoslave de)", "MK"),
    MDG("MDG", "Madagascar", "450", "Madagascar", "MG"),
    MWI("MWI", "Malawi", "454", "Malawi (le)", "MW"),
    MYS("MYS", "Malaysia", "458", "Malaisie (la)", "MY"),
    MDV("MDV", "Maldives", "462", "Maldives (les)", "MV"),
    MLI("MLI", "Mali", "466", "Mali (le)", "ML"),
    MLT("MLT", "Malta", "470", "Malte", "MT"),
    MHL("MHL", "Marshall Islands (the)", "584", "Marshall (\u00celes)", "MH"),
    MTQ("MTQ", "Martinique", "474", "Martinique (la)", "MQ"),
    MRT("MRT", "Mauritania", "478", "Mauritanie (la)", "MR"),
    MUS("MUS", "Mauritius", "480", "Maurice", "MU"),
    MYT("MYT", "Mayotte", "175", "Mayotte", "YT"),
    MEX("MEX", "Mexico", "484", "Mexique (le)", "MX"),
    FSM("FSM", "Micronesia (Federated States of)", "583", "Micron\u00e9sie (\u00c9tats f\u00e9d\u00e9r\u00e9s de)", "FM"),
    MDA("MDA", "Moldova (the Republic of)", "498", "Moldova, R\u00e9publique de", "MD"),
    MCO("MCO", "Monaco", "492", "Monaco", "MC"),
    MNG("MNG", "Mongolia", "496", "Mongolie (la)", "MN"),
    MNE("MNE", "Montenegro", "499", "Mont\u00e9n\u00e9gro (le)", "ME"),
    MSR("MSR", "Montserrat", "500", "Montserrat", "MS"),
    MAR("MAR", "Morocco", "504", "Maroc (le)", "MA"),
    MOZ("MOZ", "Mozambique", "508", "Mozambique (le)", "MZ"),
    MMR("MMR", "Myanmar", "104", "Myanmar (le)", "MM"),
    NAM("NAM", "Namibia", "516", "Namibie (la)", "NA"),
    NRU("NRU", "Nauru", "520", "Nauru", "NR"),
    NPL("NPL", "Nepal", "524", "N\u00e9pal (le)", "NP"),
    NLD("NLD", "Netherlands (the)", "528", "Pays-Bas (les)", "NL"),
    NCL("NCL", "New Caledonia", "540", "Nouvelle-Cal\u00e9donie (la)", "NC"),
    NZL("NZL", "New Zealand", "554", "Nouvelle-Z\u00e9lande (la)", "NZ"),
    NIC("NIC", "Nicaragua", "558", "Nicaragua (le)", "NI"),
    NER("NER", "Niger (the)", "562", "Niger (le)", "NE"),
    NGA("NGA", "Nigeria", "566", "Nig\u00e9ria (le)", "NG"),
    NIU("NIU", "Niue", "570", "Niue", "NU"),
    NFK("NFK", "Norfolk Island", "574", "Norfolk (l'\u00cele)", "NF"),
    MNP("MNP", "Northern Mariana Islands (the)", "580", "Mariannes du Nord (les \u00celes)", "MP"),
    NOR("NOR", "Norway", "578", "Norv\u00e8ge (la)", "NO"),
    OMN("OMN", "Oman", "512", "Oman", "OM"),
    PAK("PAK", "Pakistan", "586", "Pakistan (le)", "PK"),
    PLW("PLW", "Palau", "585", "Palaos (les)", "PW"),
    PSE("PSE", "Palestine, State of", "275", "Palestine, \u00c9tat de", "PS"),
    PAN("PAN", "Panama", "591", "Panama (le)", "PA"),
    PNG("PNG", "Papua New Guinea", "598", "Papouasie-Nouvelle-Guin\u00e9e (la)", "PG"),
    PRY("PRY", "Paraguay", "600", "Paraguay (le)", "PY"),
    PER("PER", "Peru", "604", "P\u00e9rou (le)", "PE"),
    PHL("PHL", "Philippines (the)", "608", "Philippines (les)", "PH"),
    PCN("PCN", "Pitcairn", "612", "Pitcairn", "PN"),
    POL("POL", "Poland", "616", "Pologne (la)", "PL"),
    PRT("PRT", "Portugal", "620", "Portugal (le)", "PT"),
    PRI("PRI", "Puerto Rico", "630", "Porto Rico", "PR"),
    QAT("QAT", "Qatar", "634", "Qatar (le)", "QA"),
    REU("REU", "R\u00e9union", "638", "R\u00e9union (La)", "RE"),
    ROU("ROU", "Romania", "642", "Roumanie (la)", "RO"),
    RUS("RUS", "Russian Federation (the)", "643", "Russie (la F\u00e9d\u00e9ration de)", "RU"),
    RWA("RWA", "Rwanda", "646", "Rwanda (le)", "RW"),
    BLM("BLM", "Saint Barth\u00e9lemy", "652", "Saint-Barth\u00e9lemy", "BL"),
    SHN("SHN", "Saint Helena, Ascension and Tristan da Cunha", "654", "Sainte-H\u00e9l\u00e8ne, Ascension et Tristan da Cunha", "SH"),
    KNA("KNA", "Saint Kitts and Nevis", "659", "Saint-Kitts-et-Nevis", "KN"),
    LCA("LCA", "Saint Lucia", "662", "Sainte-Lucie", "LC"),
    MAF("MAF", "Saint Martin (French part)", "663", "Saint-Martin (partie fran\u00e7aise)", "MF"),
    SPM("SPM", "Saint Pierre and Miquelon", "666", "Saint-Pierre-et-Miquelon", "PM"),
    VCT("VCT", "Saint Vincent and the Grenadines", "670", "Saint-Vincent-et-les Grenadines", "VC"),
    WSM("WSM", "Samoa", "882", "Samoa (le)", "WS"),
    SMR("SMR", "San Marino", "674", "Saint-Marin", "SM"),
    STP("STP", "Sao Tome and Principe", "678", "Sao Tom\u00e9-et-Principe", "ST"),
    SAU("SAU", "Saudi Arabia", "682", "Arabie saoudite (l')", "SA"),
    SEN("SEN", "Senegal", "686", "S\u00e9n\u00e9gal (le)", "SN"),
    SRB("SRB", "Serbia", "688", "Serbie (la)", "RS"),
    SYC("SYC", "Seychelles", "690", "Seychelles (les)", "SC"),
    SLE("SLE", "Sierra Leone", "694", "Sierra Leone (la)", "SL"),
    SGP("SGP", "Singapore", "702", "Singapour", "SG"),
    SXM("SXM", "Sint Maarten (Dutch part)", "534", "Saint-Martin (partie n\u00e9erlandaise)", "SX"),
    SVK("SVK", "Slovakia", "703", "Slovaquie (la)", "SK"),
    SVN("SVN", "Slovenia", "705", "Slov\u00e9nie (la)", "SI"),
    SLB("SLB", "Solomon Islands", "090", "Salomon (\u00celes)", "SB"),
    SOM("SOM", "Somalia", "706", "Somalie (la)", "SO"),
    ZAF("ZAF", "South Africa", "710", "Afrique du Sud (l')", "ZA"),
    SGS("SGS", "South Georgia and the South Sandwich Islands", "239", "G\u00e9orgie du Sud-et-les \u00celes Sandwich du Sud (la)", "GS"),
    SSD("SSD", "South Sudan", "728", "Soudan du Sud (le)", "SS"),
    ESP("ESP", "Spain", "724", "Espagne (l')", "ES"),
    LKA("LKA", "Sri Lanka", "144", "Sri Lanka", "LK"),
    SDN("SDN", "Sudan (the)", "729", "Soudan (le)", "SD"),
    SUR("SUR", "Suriname", "740", "Suriname (le)", "SR"),
    SJM("SJM", "Svalbard and Jan Mayen", "744", "Svalbard et l'\u00cele Jan Mayen (le)", "SJ"),
    SWZ("SWZ", "Swaziland", "748", "Swaziland (le)", "SZ"),
    SWE("SWE", "Sweden", "752", "Su\u00e8de (la)", "SE"),
    CHE("CHE", "Switzerland", "756", "Suisse (la)", "CH"),
    SYR("SYR", "Syrian Arab Republic", "760", "R\u00e9publique arabe syrienne (la)", "SY"),
    TWN("TWN", "Taiwan (Province of China)", "158", "Ta\u00efwan (Province de Chine)", "TW"),
    TJK("TJK", "Tajikistan", "762", "Tadjikistan (le)", "TJ"),
    TZA("TZA", "Tanzania, United Republic of", "834", "Tanzanie, R\u00e9publique-Unie de", "TZ"),
    THA("THA", "Thailand", "764", "Tha\u00eflande (la)", "TH"),
    TLS("TLS", "Timor-Leste", "626", "Timor-Leste (le)", "TL"),
    TGO("TGO", "Togo", "768", "Togo (le)", "TG"),
    TKL("TKL", "Tokelau", "772", "Tokelau (les)", "TK"),
    TON("TON", "Tonga", "776", "Tonga (les)", "TO"),
    TTO("TTO", "Trinidad and Tobago", "780", "Trinit\u00e9-et-Tobago (la)", "TT"),
    TUN("TUN", "Tunisia", "788", "Tunisie (la)", "TN"),
    TUR("TUR", "Turkey", "792", "Turquie (la)", "TR"),
    TKM("TKM", "Turkmenistan", "795", "Turkm\u00e9nistan (le)", "TM"),
    TCA("TCA", "Turks and Caicos Islands (the)", "796", "Turks-et-Ca\u00efcos (les \u00celes)", "TC"),
    TUV("TUV", "Tuvalu", "798", "Tuvalu (les)", "TV"),
    UGA("UGA", "Uganda", "800", "Ouganda (l')", "UG"),
    UKR("UKR", "Ukraine", "804", "Ukraine (l')", "UA"),
    ARE("ARE", "United Arab Emirates (the)", "784", "\u00c9mirats arabes unis (les)", "AE"),
    GBR("GBR", "United Kingdom of Great Britain and Northern Ireland (the)", "826", "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)", "GB"),
    UMI("UMI", "United States Minor Outlying Islands (the)", "581", "\u00celes mineures \u00e9loign\u00e9es des \u00c9tats-Unis (les)", "UM"),
    USA("USA", "United States of America (the)", "840", "\u00c9tats-Unis d'Am\u00e9rique (les)", "US"),
    URY("URY", "Uruguay", "858", "Uruguay (l')", "UY"),
    UZB("UZB", "Uzbekistan", "860", "Ouzb\u00e9kistan (l')", "UZ"),
    VUT("VUT", "Vanuatu", "548", "Vanuatu (le)", "VU"),
    VEN("VEN", "Venezuela (Bolivarian Republic of)", "862", "Venezuela (R\u00e9publique bolivarienne du)", "VE"),
    VNM("VNM", "Viet Nam", "704", "Viet Nam (le)", "VN"),
    VGB("VGB", "Virgin Islands (British)", "092", "Vierges britanniques (les\u00a0\u00celes)", "VG"),
    VIR("VIR", "Virgin Islands (U.S.)", "850", "Vierges des \u00c9tats-Unis (les \u00celes)", "VI"),
    WLF("WLF", "Wallis and Futuna", "876", "Wallis-et-Futuna\u00a0", "WF"),
    ESH("ESH", "Western Sahara*", "732", "Sahara occidental (le)*", "EH"),
    YEM("YEM", "Yemen", "887", "Y\u00e9men (le)", "YE"),
    ZMB("ZMB", "Zambia", "894", "Zambie (la)", "ZM"),
    ZWE("ZWE", "Zimbabwe", "716", "Zimbabwe (le)", "ZW");
    private final String m_sID;
    private final String m_sDisplayName;
    private final String m_sNumericcode;
    private final String m_sFrench;
    private final String m_sRef;

    private ECountryIdentificationCode22(
        @Nonnull
        @Nonempty
        final String sID,
        @Nonnull
        final String sDisplayName,
        @Nullable
        final String sNumericcode,
        @Nullable
        final String sFrench,
        @Nullable
        final String sRef) {
        m_sID = sID;
        m_sDisplayName = sDisplayName;
        m_sNumericcode = sNumericcode;
        m_sFrench = sFrench;
        m_sRef = sRef;
    }

    @Nonnull
    @Nonempty
    public String getID() {
        return m_sID;
    }

    @Nonnull
    public String getDisplayName() {
        return m_sDisplayName;
    }

    @Nullable
    public String getNumericcode() {
        return m_sNumericcode;
    }

    @Nullable
    public String getFrench() {
        return m_sFrench;
    }

    @Nullable
    public String getRef() {
        return m_sRef;
    }

    @Nullable
    public static ECountryIdentificationCode22 getFromIDOrNull(
        @Nullable
        final String sID) {
        return EnumHelper.getFromIDOrNull(ECountryIdentificationCode22 .class, sID);
    }

    @Nullable
    public static String getDisplayNameFromIDOrNull(
        @Nullable
        final String sID) {
        final ECountryIdentificationCode22 eValue = ECountryIdentificationCode22 .getFromIDOrNull(sID);
        return ((eValue == null)?null:eValue.getDisplayName());
    }
}
