/**
 * Copyright (C) 2014-2017 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.helger.ubl22.codelist;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.helger.commons.annotation.CodingStyleguideUnaware;
import com.helger.commons.annotation.Nonempty;
import com.helger.commons.id.IHasID;
import com.helger.commons.lang.EnumHelper;
import com.helger.commons.name.IHasDisplayName;


/**
 * This file was automatically generated from Genericode file LanguageCode-2.2.gc. Do NOT edit!
 * It contains a total of 922 entries!
 * @author com.helger.ubl22.main.MainCreateEnumsGenericode22
 */
@CodingStyleguideUnaware
public enum ELanguageCode22
    implements IHasID<String> , IHasDisplayName
{
    AAR("AAR", "Afar", "afar", "Danakil-Sprache", "AA"),
    AA("AA", "Afar", "afar", "Danakil-Sprache", "AAR"),
    ABK("ABK", "Abkhazian", "abkhaze", "Abchasisch", "AB"),
    AB("AB", "Abkhazian", "abkhaze", "Abchasisch", "ABK"),
    ACE("ACE", "aceh", "Aceh-Sprache", null, "ACHINESE"),
    ACHINESE("ACHINESE", "aceh", "Aceh-Sprache", null, "ACE"),
    ACH("ACH", "acoli", "Acholi-Sprache", null, "ACOLI"),
    ACOLI("ACOLI", "acoli", "Acholi-Sprache", null, "ACH"),
    ADA("ADA", "adangme", "Adangme-Sprache", "Adygisch", "ADANGME"),
    ADANGME("ADANGME", "adangme", "Adangme-Sprache", "Adygisch", "ADA"),
    ADY("ADY", "Adyghe; Adygei", "adygh\u00e9", "Adygisch", null),
    AFA("AFA", "Afro-Asiatic languages", "afro-asiatiques, langues", "Hamitosemitische Sprachen (Andere)", "AFRIHILI"),
    AFH("AFH", "afrihili", "Afrihili", "Afrikaans", "AFRIHILI"),
    AFRIHILI("AFRIHILI", "afrihili", "Afrihili", "Afrikaans", "AFH"),
    AFR("AFR", "Afrikaans", "afrikaans", "Afrikaans", "AF"),
    AF("AF", "Afrikaans", "afrikaans", "Afrikaans", "AFR"),
    AIN("AIN", "a\u00efnou", "Ainu-Sprache", "Akan-Sprache", "AINU"),
    AINU("AINU", "a\u00efnou", "Ainu-Sprache", "Akan-Sprache", "AIN"),
    AKA("AKA", "Akan", "akan", "Akan-Sprache", "AK"),
    AK("AK", "Akan", "akan", "Akan-Sprache", "AKA"),
    AKK("AKK", "akkadien", "Akkadisch", null, "AKKADIAN"),
    AKKADIAN("AKKADIAN", "akkadien", "Akkadisch", null, "AKK"),
    ALB("ALB", "Albanian", "albanais", "Albanisch", "SQ"),
    SQI("SQI", "Albanian", "albanais", "Albanisch", "SQ"),
    SQ("SQ", "Albanian", "albanais", "Albanisch", "SQI"),
    ALE("ALE", "al\u00e9oute", "Aleutisch", "Algonkin-Sprachen (Andere)", "ALEUT"),
    ALEUT("ALEUT", "al\u00e9oute", "Aleutisch", "Algonkin-Sprachen (Andere)", "ALE"),
    ALG("ALG", "Algonquian languages", "algonquines, langues", "Algonkin-Sprachen (Andere)", null),
    ALT("ALT", "Southern Altai", "altai du Sud", "Altaisch", "AM"),
    AMH("AMH", "Amharic", "amharique", "Amharisch", "AM"),
    AM("AM", "Amharic", "amharique", "Amharisch", "AMH"),
    ANG("ANG", "English, Old (ca.450-1100)", "anglo-saxon (ca.450-1100)", "Altenglisch", "ANGIKA"),
    ANP("ANP", "angika", "Anga-Sprache", "Apachen-Sprachen", "ANGIKA"),
    ANGIKA("ANGIKA", "angika", "Anga-Sprache", "Apachen-Sprachen", "ANP"),
    APA("APA", "Apache languages", "apaches, langues", "Apachen-Sprachen", "AR"),
    ARA("ARA", "Arabic", "arabe", "Arabisch", "AR"),
    AR("AR", "Arabic", "arabe", "Arabisch", "ARA"),
    ARC("ARC", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)", "aram\u00e9en d'empire (700-300 BCE)", "Aram\u00e4isch", "AN"),
    ARG("ARG", "Aragonese", "aragonais", "Aragonesisch", "AN"),
    AN("AN", "Aragonese", "aragonais", "Aragonesisch", "ARG"),
    ARM("ARM", "Armenian", "arm\u00e9nien", "Armenisch", "HY"),
    HYE("HYE", "Armenian", "arm\u00e9nien", "Armenisch", "HY"),
    HY("HY", "Armenian", "arm\u00e9nien", "Armenisch", "HYE"),
    ARN("ARN", "Mapudungun; Mapuche", "mapudungun; mapuche; mapuce", "Arauka-Sprachen", "ARAPAHO"),
    ARP("ARP", "arapaho", "Arapaho-Sprache", "Kunstsprachen (Andere)", "ARAPAHO"),
    ARAPAHO("ARAPAHO", "arapaho", "Arapaho-Sprache", "Kunstsprachen (Andere)", "ARP"),
    ART("ART", "Artificial languages", "artificielles, langues", "Kunstsprachen (Andere)", "ARAWAK"),
    ARW("ARW", "arawak", "Arawak-Sprachen", "Assamesisch", "ARAWAK"),
    ARAWAK("ARAWAK", "arawak", "Arawak-Sprachen", "Assamesisch", "ARW"),
    ASM("ASM", "Assamese", "assamais", "Assamesisch", "AS"),
    AS("AS", "Assamese", "assamais", "Assamesisch", "ASM"),
    AST("AST", "Asturian; Bable; Leonese; Asturleonese", "asturien; bable; l\u00e9onais; asturol\u00e9onais", "Asturisch", null),
    ATH("ATH", "Athapascan languages", "athapascanes, langues", "Athapaskische Sprachen (Andere)", null),
    AUS("AUS", "Australian languages", "australiennes, langues", "Australische Sprachen", "AV"),
    AVA("AVA", "Avaric", "avar", "Awarisch", "AV"),
    AV("AV", "Avaric", "avar", "Awarisch", "AVA"),
    AVE("AVE", "Avestan", "avestique", "Avestisch", "AE"),
    AE("AE", "Avestan", "avestique", "Avestisch", "AVE"),
    AWA("AWA", "awadhi", "Awadhi", "Aymar\u00e1-Sprache", "AWADHI"),
    AWADHI("AWADHI", "awadhi", "Awadhi", "Aymar\u00e1-Sprache", "AWA"),
    AYM("AYM", "Aymara", "aymara", "Aymar\u00e1-Sprache", "AY"),
    AY("AY", "Aymara", "aymara", "Aymar\u00e1-Sprache", "AYM"),
    AZE("AZE", "Azerbaijani", "az\u00e9ri", "Aserbeidschanisch", "AZ"),
    AZ("AZ", "Azerbaijani", "az\u00e9ri", "Aserbeidschanisch", "AZE"),
    BAD("BAD", "Banda languages", "banda, langues", "Banda-Sprachen (Ubangi-Sprachen)", null),
    BAI("BAI", "Bamileke languages", "bamil\u00e9k\u00e9, langues", "Bamileke-Sprachen", "BA"),
    BAK("BAK", "Bashkir", "bachkir", "Baschkirisch", "BA"),
    BA("BA", "Bashkir", "bachkir", "Baschkirisch", "BAK"),
    BAL("BAL", "baloutchi", "Belutschisch", "Bambara-Sprache", "BALUCHI"),
    BALUCHI("BALUCHI", "baloutchi", "Belutschisch", "Bambara-Sprache", "BAL"),
    BAM("BAM", "Bambara", "bambara", "Bambara-Sprache", "BM"),
    BM("BM", "Bambara", "bambara", "Bambara-Sprache", "BAM"),
    BAN("BAN", "balinais", "Balinesisch", null, "BALINESE"),
    BALINESE("BALINESE", "balinais", "Balinesisch", null, "BAN"),
    BAQ("BAQ", "Basque", "basque", "Baskisch", "EU"),
    EUS("EUS", "Basque", "basque", "Baskisch", "EU"),
    EU("EU", "Basque", "basque", "Baskisch", "EUS"),
    BAS("BAS", "basa", "Basaa-Sprache", "Baltische Sprachen (Andere)", "BASA"),
    BASA("BASA", "basa", "Basaa-Sprache", "Baltische Sprachen (Andere)", "BAS"),
    BAT("BAT", "Baltic languages", "baltes, langues", "Baltische Sprachen (Andere)", null),
    BEJ("BEJ", "Beja; Bedawiyet", "bedja", "Bedauye", "BE"),
    BEL("BEL", "Belarusian", "bi\u00e9lorusse", "Wei\u00dfrussisch", "BE"),
    BE("BE", "Belarusian", "bi\u00e9lorusse", "Wei\u00dfrussisch", "BEL"),
    BEM("BEM", "bemba", "Bemba-Sprache", "Bengali", "BEMBA"),
    BEMBA("BEMBA", "bemba", "Bemba-Sprache", "Bengali", "BEM"),
    BEN("BEN", "Bengali", "bengali", "Bengali", "BN"),
    BN("BN", "Bengali", "bengali", "Bengali", "BEN"),
    BER("BER", "Berber languages", "berb\u00e8res, langues", "Berbersprachen (Andere)", "BHOJPURI"),
    BHO("BHO", "bhojpuri", "Bhojpuri", "Bihari (Andere)", "BHOJPURI"),
    BHOJPURI("BHOJPURI", "bhojpuri", "Bhojpuri", "Bihari (Andere)", "BHO"),
    BIH("BIH", "Bihari languages", "langues biharis", "Bihari (Andere)", "BH"),
    BH("BH", "Bihari languages", "langues biharis", "Bihari (Andere)", "BIH"),
    BIK("BIK", "bikol", "Bikol-Sprache", "Edo-Sprache", "BIKOL"),
    BIKOL("BIKOL", "bikol", "Bikol-Sprache", "Edo-Sprache", "BIK"),
    BIN("BIN", "Bini; Edo", "bini; edo", "Edo-Sprache", "BI"),
    BIS("BIS", "Bislama", "bichlamar", "Beach-la-mar", "BI"),
    BI("BI", "Bislama", "bichlamar", "Beach-la-mar", "BIS"),
    BLA("BLA", "blackfoot", "Blackfoot-Sprache", "Bantusprachen (Andere)", "SIKSIKA"),
    SIKSIKA("SIKSIKA", "blackfoot", "Blackfoot-Sprache", "Bantusprachen (Andere)", "BLA"),
    BNT("BNT", "Bantu languages", "bantou, langues", "Bantusprachen (Andere)", null),
    TIB("TIB", "Tibetan", "tib\u00e9tain", "Tibetisch", "BO"),
    BOD("BOD", "Tibetan", "tib\u00e9tain", "Tibetisch", "BO"),
    BO("BO", "Tibetan", "tib\u00e9tain", "Tibetisch", "BOD"),
    BOS("BOS", "Bosnian", "bosniaque", "Bosnisch", "BS"),
    BS("BS", "Bosnian", "bosniaque", "Bosnisch", "BOS"),
    BRA("BRA", "braj", "Braj-Bhakha", "Bretonisch", "BRAJ"),
    BRAJ("BRAJ", "braj", "Braj-Bhakha", "Bretonisch", "BRA"),
    BRE("BRE", "Breton", "breton", "Bretonisch", "BR"),
    BR("BR", "Breton", "breton", "Bretonisch", "BRE"),
    BTK("BTK", "Batak languages", "batak, langues", "Batak-Sprache", "BURIAT"),
    BUA("BUA", "bouriate", "Burjatisch", null, "BURIAT"),
    BURIAT("BURIAT", "bouriate", "Burjatisch", null, "BUA"),
    BUG("BUG", "bugi", "Bugi-Sprache", "Bulgarisch", "BUGINESE"),
    BUGINESE("BUGINESE", "bugi", "Bugi-Sprache", "Bulgarisch", "BUG"),
    BUL("BUL", "Bulgarian", "bulgare", "Bulgarisch", "BG"),
    BG("BG", "Bulgarian", "bulgare", "Bulgarisch", "BUL"),
    BUR("BUR", "Burmese", "birman", "Birmanisch", "MY"),
    MYA("MYA", "Burmese", "birman", "Birmanisch", "MY"),
    MY("MY", "Burmese", "birman", "Birmanisch", "MYA"),
    BYN("BYN", "Blin; Bilin", "blin; bilen", "Bilin-Sprache", "CADDO"),
    CAD("CAD", "caddo", "Caddo-Sprachen", "Indianersprachen, Zentralamerika (Andere)", "CADDO"),
    CADDO("CADDO", "caddo", "Caddo-Sprachen", "Indianersprachen, Zentralamerika (Andere)", "CAD"),
    CAI("CAI", "Central American Indian languages", "am\u00e9rindiennes de l'Am\u00e9rique centrale, langues", "Indianersprachen, Zentralamerika (Andere)", null),
    CAR("CAR", "Galibi Carib", "karib; galibi; carib", "Karibische Sprachen", "CA"),
    CAT("CAT", "Catalan; Valencian", "catalan; valencien", "Katalanisch", "CA"),
    CA("CA", "Catalan; Valencian", "catalan; valencien", "Katalanisch", "CAT"),
    CAU("CAU", "Caucasian languages", "caucasiennes, langues", "Kaukasische Sprachen (Andere)", "CEBUANO"),
    CEB("CEB", "cebuano", "Cebuano", "Keltische Sprachen (Andere)", "CEBUANO"),
    CEBUANO("CEBUANO", "cebuano", "Cebuano", "Keltische Sprachen (Andere)", "CEB"),
    CEL("CEL", "Celtic languages", "celtiques, langues; celtes, langues", "Keltische Sprachen (Andere)", null),
    CZE("CZE", "Czech", "tch\u00e8que", "Tschechisch", "CS"),
    CES("CES", "Czech", "tch\u00e8que", "Tschechisch", "CS"),
    CS("CS", "Czech", "tch\u00e8que", "Tschechisch", "CES"),
    CHA("CHA", "Chamorro", "chamorro", "Chamorro-Sprache", "CH"),
    CH("CH", "Chamorro", "chamorro", "Chamorro-Sprache", "CHA"),
    CHB("CHB", "chibcha", "Chibcha-Sprachen", "Tschetschenisch", "CHIBCHA"),
    CHIBCHA("CHIBCHA", "chibcha", "Chibcha-Sprachen", "Tschetschenisch", "CHB"),
    CHE("CHE", "Chechen", "tch\u00e9tch\u00e8ne", "Tschetschenisch", "CE"),
    CE("CE", "Chechen", "tch\u00e9tch\u00e8ne", "Tschetschenisch", "CHE"),
    CHG("CHG", "djaghata\u00ef", "Tschagataisch", null, "CHAGATAI"),
    CHAGATAI("CHAGATAI", "djaghata\u00ef", "Tschagataisch", null, "CHG"),
    CHI("CHI", "Chinese", "chinois", "Chinesisch", "ZH"),
    ZHO("ZHO", "Chinese", "chinois", "Chinesisch", "ZH"),
    ZH("ZH", "Chinese", "chinois", "Chinesisch", "ZHO"),
    CHK("CHK", "chuuk", "Trukesisch", null, "CHUUKESE"),
    CHUUKESE("CHUUKESE", "chuuk", "Trukesisch", null, "CHK"),
    CHM("CHM", "mari", "Tscheremissisch", "Chinook-Jargon", "MARI"),
    MARI("MARI", "mari", "Tscheremissisch", "Chinook-Jargon", "CHM"),
    CHN("CHN", "Chinook jargon", "chinook, jargon", "Chinook-Jargon", "CHOCTAW"),
    CHO("CHO", "choctaw", "Choctaw-Sprache", "Chipewyan-Sprache", "CHOCTAW"),
    CHOCTAW("CHOCTAW", "choctaw", "Choctaw-Sprache", "Chipewyan-Sprache", "CHO"),
    CHP("CHP", "Chipewyan; Dene Suline", "chipewyan", "Chipewyan-Sprache", "CHEROKEE"),
    CHR("CHR", "cherokee", "Cherokee-Sprache", "Kirchenslawisch", "CHEROKEE"),
    CHEROKEE("CHEROKEE", "cherokee", "Cherokee-Sprache", "Kirchenslawisch", "CHR"),
    CHU("CHU", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", "slavon d'\u00e9glise; vieux slave; slavon liturgique; vieux bulgare", "Kirchenslawisch", "CU"),
    CU("CU", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", "slavon d'\u00e9glise; vieux slave; slavon liturgique; vieux bulgare", "Kirchenslawisch", "CHU"),
    CHV("CHV", "Chuvash", "tchouvache", "Tschuwaschisch", "CV"),
    CV("CV", "Chuvash", "tchouvache", "Tschuwaschisch", "CHV"),
    CHY("CHY", "cheyenne", "Cheyenne-Sprache", "Cham-Sprachen", "CHEYENNE"),
    CHEYENNE("CHEYENNE", "cheyenne", "Cheyenne-Sprache", "Cham-Sprachen", "CHY"),
    CMC("CMC", "Chamic languages", "chames, langues", "Cham-Sprachen", "COPTIC"),
    COP("COP", "copte", "Koptisch", "Kornisch", "COPTIC"),
    COPTIC("COPTIC", "copte", "Koptisch", "Kornisch", "COP"),
    COR("COR", "Cornish", "cornique", "Kornisch", "KW"),
    KW("KW", "Cornish", "cornique", "Kornisch", "COR"),
    COS("COS", "Corsican", "corse", "Korsisch", "CO"),
    CO("CO", "Corsican", "corse", "Korsisch", "COS"),
    CPE("CPE", "Creoles and pidgins, English based", "cr\u00e9oles et pidgins bas\u00e9s sur l'anglais", "Kreolisch-Englisch (Andere)", null),
    CPF("CPF", "Creoles and pidgins, French-based", "cr\u00e9oles et pidgins bas\u00e9s sur le fran\u00e7ais", "Kreolisch-Franz\u00f6sisch (Andere)", null),
    CPP("CPP", "Creoles and pidgins, Portuguese-based", "cr\u00e9oles et pidgins bas\u00e9s sur le portugais", "Kreolisch-Portugiesisch (Andere)", "CR"),
    CRE("CRE", "Cree", "cree", "Cree-Sprache", "CR"),
    CR("CR", "Cree", "cree", "Cree-Sprache", "CRE"),
    CRH("CRH", "Crimean Tatar; Crimean Turkish", "tatar de Crim\u00e9", "Krimtatarisch", null),
    CRP("CRP", "Creoles and pidgins", "cr\u00e9oles et pidgins", "Kreolische Sprachen; Pidginsprachen (Andere)", "KASHUBIAN"),
    CSB("CSB", "kachoube", "Kaschubisch", "Kuschitische Sprachen (Andere)", "KASHUBIAN"),
    KASHUBIAN("KASHUBIAN", "kachoube", "Kaschubisch", "Kuschitische Sprachen (Andere)", "CSB"),
    CUS("CUS", "Cushitic languages", "couchitiques, langues", "Kuschitische Sprachen (Andere)", null),
    WEL("WEL", "Welsh", "gallois", "Kymrisch", "CY"),
    CYM("CYM", "Welsh", "gallois", "Kymrisch", "CY"),
    CY("CY", "Welsh", "gallois", "Kymrisch", "CYM"),
    CZE_1("CZE", "Czech", "tch\u00e8que", "Tschechisch", "CS"),
    CES_1("CES", "Czech", "tch\u00e8que", "Tschechisch", "CS"),
    CS_1("CS", "Czech", "tch\u00e8que", "Tschechisch", "CES"),
    DAK("DAK", "dakota", "Dakota-Sprache", "D\u00e4nisch", "DAKOTA"),
    DAKOTA("DAKOTA", "dakota", "Dakota-Sprache", "D\u00e4nisch", "DAK"),
    DAN("DAN", "Danish", "danois", "D\u00e4nisch", "DA"),
    DA("DA", "Danish", "danois", "D\u00e4nisch", "DAN"),
    DAR("DAR", "dargwa", "Darginisch", "Dajakisch", "DARGWA"),
    DARGWA("DARGWA", "dargwa", "Darginisch", "Dajakisch", "DAR"),
    DAY("DAY", "Land Dayak languages", "dayak, langues", "Dajakisch", "DELAWARE"),
    DEL("DEL", "delaware", "Delaware-Sprache", "Slave-Sprache", "DELAWARE"),
    DELAWARE("DELAWARE", "delaware", "Delaware-Sprache", "Slave-Sprache", "DEL"),
    DEN("DEN", "Slave (Athapascan)", "esclave (athapascan)", "Slave-Sprache", null),
    GER("GER", "German", "allemand", "Deutsch", "DE"),
    DEU("DEU", "German", "allemand", "Deutsch", "DE"),
    DE("DE", "German", "allemand", "Deutsch", "DEU"),
    DGR("DGR", "dogrib", "Dogrib-Sprache", null, "DOGRIB"),
    DOGRIB("DOGRIB", "dogrib", "Dogrib-Sprache", null, "DGR"),
    DIN("DIN", "dinka", "Dinka-Sprache", "Maledivisch", "DINKA"),
    DINKA("DINKA", "dinka", "Dinka-Sprache", "Maledivisch", "DIN"),
    DIV("DIV", "Divehi; Dhivehi; Maldivian", "maldivien", "Maledivisch", "DV"),
    DV("DV", "Divehi; Dhivehi; Maldivian", "maldivien", "Maledivisch", "DIV"),
    DOI("DOI", "dogri", "Dogri", "Drawidische Sprachen (Andere)", "DOGRI"),
    DOGRI("DOGRI", "dogri", "Dogri", "Drawidische Sprachen (Andere)", "DOI"),
    DRA("DRA", "Dravidian languages", "dravidiennes, langues", "Drawidische Sprachen (Andere)", null),
    DSB("DSB", "Lower Sorbian", "bas-sorabe", "Niedersorbisch", "DUALA"),
    DUA("DUA", "douala", "Duala-Sprachen", "Mittelniederl\u00e4ndisch", "DUALA"),
    DUALA("DUALA", "douala", "Duala-Sprachen", "Mittelniederl\u00e4ndisch", "DUA"),
    DUM("DUM", "Dutch, Middle (ca.1050-1350)", "n\u00e9erlandais moyen (ca. 1050-1350)", "Mittelniederl\u00e4ndisch", null),
    DUT("DUT", "Dutch; Flemish", "n\u00e9erlandais; flamand", "Niederl\u00e4ndisch", "NL"),
    NLD("NLD", "Dutch; Flemish", "n\u00e9erlandais; flamand", "Niederl\u00e4ndisch", "NL"),
    NL("NL", "Dutch; Flemish", "n\u00e9erlandais; flamand", "Niederl\u00e4ndisch", "NLD"),
    DYU("DYU", "dioula", "Dyula-Sprache", "Dzongkha", "DYULA"),
    DYULA("DYULA", "dioula", "Dyula-Sprache", "Dzongkha", "DYU"),
    DZO("DZO", "Dzongkha", "dzongkha", "Dzongkha", "DZ"),
    DZ("DZ", "Dzongkha", "dzongkha", "Dzongkha", "DZO"),
    EFI("EFI", "efik", "Efik", "\u00c4gyptisch", "EFIK"),
    EFIK("EFIK", "efik", "Efik", "\u00c4gyptisch", "EFI"),
    EGY("EGY", "Egyptian (Ancient)", "\u00e9gyptien", "\u00c4gyptisch", "EKAJUK"),
    EKA("EKA", "ekajuk", "Ekajuk", null, "EKAJUK"),
    EKAJUK("EKAJUK", "ekajuk", "Ekajuk", null, "EKA"),
    GRE("GRE", "Greek, Modern (1453-)", "grec moderne (apr\u00e8s 1453)", "Neugriechisch", "EL"),
    ELL("ELL", "Greek, Modern (1453-)", "grec moderne (apr\u00e8s 1453)", "Neugriechisch", "EL"),
    EL("EL", "Greek, Modern (1453-)", "grec moderne (apr\u00e8s 1453)", "Neugriechisch", "ELL"),
    ELX("ELX", "\u00e9lamite", "Elamisch", "Englisch", "ELAMITE"),
    ELAMITE("ELAMITE", "\u00e9lamite", "Elamisch", "Englisch", "ELX"),
    ENG("ENG", "English", "anglais", "Englisch", "EN"),
    EN("EN", "English", "anglais", "Englisch", "ENG"),
    ENM("ENM", "English, Middle (1100-1500)", "anglais moyen (1100-1500)", "Mittelenglisch", "EO"),
    EPO("EPO", "Esperanto", "esp\u00e9ranto", "Esperanto", "EO"),
    EO("EO", "Esperanto", "esp\u00e9ranto", "Esperanto", "EPO"),
    EST("EST", "Estonian", "estonien", "Estnisch", "ET"),
    ET("ET", "Estonian", "estonien", "Estnisch", "EST"),
    BAQ_1("BAQ", "Basque", "basque", "Baskisch", "EU"),
    EUS_1("EUS", "Basque", "basque", "Baskisch", "EU"),
    EU_1("EU", "Basque", "basque", "Baskisch", "EUS"),
    EWE("EWE", "Ewe", "\u00e9w\u00e9", "Ewe-Sprache", "EE"),
    EE("EE", "Ewe", "\u00e9w\u00e9", "Ewe-Sprache", "EWE"),
    EWO("EWO", "\u00e9wondo", "Ewondo", null, "EWONDO"),
    EWONDO("EWONDO", "\u00e9wondo", "Ewondo", null, "EWO"),
    FAN("FAN", "fang", "Pangwe-Sprache", "F\u00e4r\u00f6isch", "FANG"),
    FANG("FANG", "fang", "Pangwe-Sprache", "F\u00e4r\u00f6isch", "FAN"),
    FAO("FAO", "Faroese", "f\u00e9ro\u00efen", "F\u00e4r\u00f6isch", "FO"),
    FO("FO", "Faroese", "f\u00e9ro\u00efen", "F\u00e4r\u00f6isch", "FAO"),
    PER("PER", "Persian", "persan", "Persisch", "FA"),
    FAS("FAS", "Persian", "persan", "Persisch", "FA"),
    FA("FA", "Persian", "persan", "Persisch", "FAS"),
    FAT("FAT", "fanti", "Fante-Sprache", "Fidschi-Sprache", "FANTI"),
    FANTI("FANTI", "fanti", "Fante-Sprache", "Fidschi-Sprache", "FAT"),
    FIJ("FIJ", "Fijian", "fidjien", "Fidschi-Sprache", "FJ"),
    FJ("FJ", "Fijian", "fidjien", "Fidschi-Sprache", "FIJ"),
    FIL("FIL", "Filipino; Pilipino", "filipino; pilipino", "Pilipino", "FI"),
    FIN("FIN", "Finnish", "finnois", "Finnisch", "FI"),
    FI("FI", "Finnish", "finnois", "Finnisch", "FIN"),
    FIU("FIU", "Finno-Ugrian languages", "finno-ougriennes, langues", "Finnougrische Sprachen (Andere)", "FON"),
    FON("FON", "fon", "Fon-Sprache", null, "FON"),
    FON_1("FON", "fon", "Fon-Sprache", null, "FON"),
    FRE("FRE", "French", "fran\u00e7ais", "Franz\u00f6sisch", "FR"),
    FRA("FRA", "French", "fran\u00e7ais", "Franz\u00f6sisch", "FR"),
    FR("FR", "French", "fran\u00e7ais", "Franz\u00f6sisch", "FRA"),
    FRE_1("FRE", "French", "fran\u00e7ais", "Franz\u00f6sisch", "FR"),
    FRA_1("FRA", "French", "fran\u00e7ais", "Franz\u00f6sisch", "FR"),
    FR_1("FR", "French", "fran\u00e7ais", "Franz\u00f6sisch", "FRA"),
    FRM("FRM", "French, Middle (ca.1400-1600)", "fran\u00e7ais moyen (1400-1600)", "Mittelfranz\u00f6sisch", null),
    FRO("FRO", "French, Old (842-ca.1400)", "fran\u00e7ais ancien (842-ca.1400)", "Altfranz\u00f6sisch", null),
    FRR("FRR", "Northern Frisian", "frison septentrional", "Nordfriesisch", null),
    FRS("FRS", "Eastern Frisian", "frison oriental", "Ostfriesisch", "FY"),
    FRY("FRY", "Western Frisian", "frison occidental", "Friesisch", "FY"),
    FY("FY", "Western Frisian", "frison occidental", "Friesisch", "FRY"),
    FUL("FUL", "Fulah", "peul", "Ful", "FF"),
    FF("FF", "Fulah", "peul", "Ful", "FUL"),
    FUR("FUR", "frioulan", "Friulisch", null, "FRIULIAN"),
    FRIULIAN("FRIULIAN", "frioulan", "Friulisch", null, "FUR"),
    GAA("GAA", "ga", "Ga-Sprache", null, "GA"),
    GA("GA", "ga", "Ga-Sprache", null, "GAA"),
    GAY("GAY", "gayo", "Gayo-Sprache", null, "GAYO"),
    GAYO("GAYO", "gayo", "Gayo-Sprache", null, "GAY"),
    GBA("GBA", "gbaya", "Gbaya-Sprache", "Germanische Sprachen (Andere)", "GBAYA"),
    GBAYA("GBAYA", "gbaya", "Gbaya-Sprache", "Germanische Sprachen (Andere)", "GBA"),
    GEM("GEM", "Germanic languages", "germaniques, langues", "Germanische Sprachen (Andere)", null),
    GEO("GEO", "Georgian", "g\u00e9orgien", "Georgisch", "KA"),
    KAT("KAT", "Georgian", "g\u00e9orgien", "Georgisch", "KA"),
    KA("KA", "Georgian", "g\u00e9orgien", "Georgisch", "KAT"),
    GER_1("GER", "German", "allemand", "Deutsch", "DE"),
    DEU_1("DEU", "German", "allemand", "Deutsch", "DE"),
    DE_1("DE", "German", "allemand", "Deutsch", "DEU"),
    GEZ("GEZ", "gu\u00e8ze", "Alt\u00e4thiopisch", null, "GEEZ"),
    GEEZ("GEEZ", "gu\u00e8ze", "Alt\u00e4thiopisch", null, "GEZ"),
    GIL("GIL", "kiribati", "Gilbertesisch", "G\u00e4lisch-Schottisch", "GILBERTESE"),
    GILBERTESE("GILBERTESE", "kiribati", "Gilbertesisch", "G\u00e4lisch-Schottisch", "GIL"),
    GLA("GLA", "Gaelic; Scottish Gaelic", "ga\u00e9lique; ga\u00e9lique \u00e9cossais", "G\u00e4lisch-Schottisch", "GD"),
    GD("GD", "Gaelic; Scottish Gaelic", "ga\u00e9lique; ga\u00e9lique \u00e9cossais", "G\u00e4lisch-Schottisch", "GLA"),
    GLE("GLE", "Irish", "irlandais", "Irisch", "GA"),
    GA_1("GA", "Irish", "irlandais", "Irisch", "GLE"),
    GLG("GLG", "Galician", "galicien", "Galicisch", "GL"),
    GL("GL", "Galician", "galicien", "Galicisch", "GLG"),
    GLV("GLV", "Manx", "manx; mannois", "Manx", "GV"),
    GV("GV", "Manx", "manx; mannois", "Manx", "GLV"),
    GMH("GMH", "German, Middle High (ca.1050-1500)", "allemand, moyen haut (ca. 1050-1500)", "Mittelhochdeutsch", null),
    GOH("GOH", "German, Old High (ca.750-1050)", "allemand, vieux haut (ca. 750-1050)", "Althochdeutsch", "GONDI"),
    GON("GON", "gond", "Gondi-Sprache", null, "GONDI"),
    GONDI("GONDI", "gond", "Gondi-Sprache", null, "GON"),
    GOR("GOR", "gorontalo", "Gorontalesisch", null, "GORONTALO"),
    GORONTALO("GORONTALO", "gorontalo", "Gorontalesisch", null, "GOR"),
    GOT("GOT", "gothique", "Gotisch", null, "GOTHIC"),
    GOTHIC("GOTHIC", "gothique", "Gotisch", null, "GOT"),
    GRB("GRB", "grebo", "Grebo-Sprache", "Griechisch", "GREBO"),
    GREBO("GREBO", "grebo", "Grebo-Sprache", "Griechisch", "GRB"),
    GRC("GRC", "Greek, Ancient (to 1453)", "grec ancien (jusqu'\u00e0 1453)", "Griechisch", null),
    GRE_1("GRE", "Greek, Modern (1453-)", "grec moderne (apr\u00e8s 1453)", "Neugriechisch", "EL"),
    ELL_1("ELL", "Greek, Modern (1453-)", "grec moderne (apr\u00e8s 1453)", "Neugriechisch", "EL"),
    EL_1("EL", "Greek, Modern (1453-)", "grec moderne (apr\u00e8s 1453)", "Neugriechisch", "ELL"),
    GRN("GRN", "Guarani", "guarani", "Guaran\u00ed-Sprache", "GN"),
    GN("GN", "Guarani", "guarani", "Guaran\u00ed-Sprache", "GRN"),
    GSW("GSW", "Swiss German; Alemannic; Alsatian", "suisse al\u00e9manique; al\u00e9manique; alsacien", "Schweizerdeutsch", "GU"),
    GUJ("GUJ", "Gujarati", "goudjrati", "Gujarati-Sprache", "GU"),
    GU("GU", "Gujarati", "goudjrati", "Gujarati-Sprache", "GUJ"),
    GWI("GWI", "gwich'in", "Kutchin-Sprache", null, "GWICH'IN"),
    GWICH_IN("GWICH'IN", "gwich'in", "Kutchin-Sprache", null, "GWI"),
    HAI("HAI", "haida", "Haida-Sprache", "Ha\u00eftien (Haiti-Kreolisch)", "HAIDA"),
    HAIDA("HAIDA", "haida", "Haida-Sprache", "Ha\u00eftien (Haiti-Kreolisch)", "HAI"),
    HAT("HAT", "Haitian; Haitian Creole", "ha\u00eftien; cr\u00e9ole ha\u00eftien", "Ha\u00eftien (Haiti-Kreolisch)", "HT"),
    HT("HT", "Haitian; Haitian Creole", "ha\u00eftien; cr\u00e9ole ha\u00eftien", "Ha\u00eftien (Haiti-Kreolisch)", "HAT"),
    HAU("HAU", "Hausa", "haoussa", "Haussa-Sprache", "HA"),
    HA("HA", "Hausa", "haoussa", "Haussa-Sprache", "HAU"),
    HAW("HAW", "hawa\u00efen", "Hawaiisch", "Hebr\u00e4isch", "HAWAIIAN"),
    HAWAIIAN("HAWAIIAN", "hawa\u00efen", "Hawaiisch", "Hebr\u00e4isch", "HAW"),
    HEB("HEB", "Hebrew", "h\u00e9breu", "Hebr\u00e4isch", "HE"),
    HE("HE", "Hebrew", "h\u00e9breu", "Hebr\u00e4isch", "HEB"),
    HER("HER", "Herero", "herero", "Herero-Sprache", "HZ"),
    HZ("HZ", "Herero", "herero", "Herero-Sprache", "HER"),
    HIL("HIL", "hiligaynon", "Hiligaynon-Sprache", "Himachali", "HILIGAYNON"),
    HILIGAYNON("HILIGAYNON", "hiligaynon", "Hiligaynon-Sprache", "Himachali", "HIL"),
    HIM("HIM", "Himachali languages; Western Pahari languages", "langues himachalis; langues paharis occidentales", "Himachali", "HI"),
    HIN("HIN", "Hindi", "hindi", "Hindi", "HI"),
    HI("HI", "Hindi", "hindi", "Hindi", "HIN"),
    HIT("HIT", "hittite", "Hethitisch", "Miao-Sprachen", "HITTITE"),
    HITTITE("HITTITE", "hittite", "Hethitisch", "Miao-Sprachen", "HIT"),
    HMN("HMN", "Hmong; Mong", "hmong", "Miao-Sprachen", "HO"),
    HMO("HMO", "Hiri Motu", "hiri motu", "Hiri-Motu", "HO"),
    HO("HO", "Hiri Motu", "hiri motu", "Hiri-Motu", "HMO"),
    HRV("HRV", "Croatian", "croate", "Kroatisch", "HR"),
    HR("HR", "Croatian", "croate", "Kroatisch", "HRV"),
    HSB("HSB", "Upper Sorbian", "haut-sorabe", "Obersorbisch", "HU"),
    HUN("HUN", "Hungarian", "hongrois", "Ungarisch", "HU"),
    HU("HU", "Hungarian", "hongrois", "Ungarisch", "HUN"),
    HUP("HUP", "hupa", "Hupa-Sprache", null, "HUPA"),
    HUPA("HUPA", "hupa", "Hupa-Sprache", null, "HUP"),
    ARM_1("ARM", "Armenian", "arm\u00e9nien", "Armenisch", "HY"),
    HYE_1("HYE", "Armenian", "arm\u00e9nien", "Armenisch", "HY"),
    HY_1("HY", "Armenian", "arm\u00e9nien", "Armenisch", "HYE"),
    IBA("IBA", "iban", "Iban-Sprache", "Ibo-Sprache", "IBAN"),
    IBAN("IBAN", "iban", "Iban-Sprache", "Ibo-Sprache", "IBA"),
    IBO("IBO", "Igbo", "igbo", "Ibo-Sprache", "IG"),
    IG("IG", "Igbo", "igbo", "Ibo-Sprache", "IBO"),
    ICE("ICE", "Icelandic", "islandais", "Isl\u00e4ndisch", "IS"),
    ISL("ISL", "Icelandic", "islandais", "Isl\u00e4ndisch", "IS"),
    IS("IS", "Icelandic", "islandais", "Isl\u00e4ndisch", "ISL"),
    IDO("IDO", "Ido", "ido", "Ido", "IO"),
    IO("IO", "Ido", "ido", "Ido", "IDO"),
    III("III", "Sichuan Yi; Nuosu", "yi de Sichuan", "Lalo-Sprache", "II"),
    II("II", "Sichuan Yi; Nuosu", "yi de Sichuan", "Lalo-Sprache", "III"),
    IJO("IJO", "Ijo languages", "ijo, langues", "Ijo-Sprache", "IU"),
    IKU("IKU", "Inuktitut", "inuktitut", "Inuktitut", "IU"),
    IU("IU", "Inuktitut", "inuktitut", "Inuktitut", "IKU"),
    ILE("ILE", "Interlingue; Occidental", "interlingue", "Interlingue", "IE"),
    IE("IE", "Interlingue; Occidental", "interlingue", "Interlingue", "ILE"),
    ILO("ILO", "ilocano", "Ilokano-Sprache", "Interlingua", "ILOKO"),
    ILOKO("ILOKO", "ilocano", "Ilokano-Sprache", "Interlingua", "ILO"),
    INA("INA", "Interlingua (International Auxiliary Language Association)", "interlingua (langue auxiliaire internationale)", "Interlingua", "IA"),
    IA("IA", "Interlingua (International Auxiliary Language Association)", "interlingua (langue auxiliaire internationale)", "Interlingua", "INA"),
    INC("INC", "Indic languages", "indo-aryennes, langues", "Indoarische Sprachen (Andere)", "ID"),
    IND("IND", "Indonesian", "indon\u00e9sien", "Bahasa Indonesia", "ID"),
    ID("ID", "Indonesian", "indon\u00e9sien", "Bahasa Indonesia", "IND"),
    INE("INE", "Indo-European languages", "indo-europ\u00e9ennes, langues", "Indogermanische Sprachen (Andere)", "INGUSH"),
    INH("INH", "ingouche", "Inguschisch", "Inupik", "INGUSH"),
    INGUSH("INGUSH", "ingouche", "Inguschisch", "Inupik", "INH"),
    IPK("IPK", "Inupiaq", "inupiaq", "Inupik", "IK"),
    IK("IK", "Inupiaq", "inupiaq", "Inupik", "IPK"),
    IRA("IRA", "Iranian languages", "iraniennes, langues", "Iranische Sprachen (Andere)", null),
    IRO("IRO", "Iroquoian languages", "iroquoises, langues", "Irokesische Sprachen", null),
    ICE_1("ICE", "Icelandic", "islandais", "Isl\u00e4ndisch", "IS"),
    ISL_1("ISL", "Icelandic", "islandais", "Isl\u00e4ndisch", "IS"),
    IS_1("IS", "Icelandic", "islandais", "Isl\u00e4ndisch", "ISL"),
    ITA("ITA", "Italian", "italien", "Italienisch", "IT"),
    IT("IT", "Italian", "italien", "Italienisch", "ITA"),
    JAV("JAV", "Javanese", "javanais", "Javanisch", "JV"),
    JV("JV", "Javanese", "javanais", "Javanisch", "JAV"),
    JBO("JBO", "lojban", "Lojban", "Japanisch", "LOJBAN"),
    LOJBAN("LOJBAN", "lojban", "Lojban", "Japanisch", "JBO"),
    JPN("JPN", "Japanese", "japonais", "Japanisch", "JA"),
    JA("JA", "Japanese", "japonais", "Japanisch", "JPN"),
    JPR("JPR", "jud\u00e9o-persan", "J\u00fcdisch-Persisch", null, "JUDEO-PERSIAN"),
    JUDEO_PERSIAN("JUDEO-PERSIAN", "jud\u00e9o-persan", "J\u00fcdisch-Persisch", null, "JPR"),
    JRB("JRB", "jud\u00e9o-arabe", "J\u00fcdisch-Arabisch", null, "JUDEO-ARABIC"),
    JUDEO_ARABIC("JUDEO-ARABIC", "jud\u00e9o-arabe", "J\u00fcdisch-Arabisch", null, "JRB"),
    KAA("KAA", "karakalpak", "Karakalpakisch", null, "KARA-KALPAK"),
    KARA_KALPAK("KARA-KALPAK", "karakalpak", "Karakalpakisch", null, "KAA"),
    KAB("KAB", "kabyle", "Kabylisch", "Kachin-Sprache", "KABYLE"),
    KABYLE("KABYLE", "kabyle", "Kabylisch", "Kachin-Sprache", "KAB"),
    KAC("KAC", "Kachin; Jingpho", "kachin; jingpho", "Kachin-Sprache", "KL"),
    KAL("KAL", "Kalaallisut; Greenlandic", "groenlandais", "Gr\u00f6nl\u00e4ndisch", "KL"),
    KL("KL", "Kalaallisut; Greenlandic", "groenlandais", "Gr\u00f6nl\u00e4ndisch", "KAL"),
    KAM("KAM", "kamba", "Kamba-Sprache", "Kannada", "KAMBA"),
    KAMBA("KAMBA", "kamba", "Kamba-Sprache", "Kannada", "KAM"),
    KAN("KAN", "Kannada", "kannada", "Kannada", "KN"),
    KN("KN", "Kannada", "kannada", "Kannada", "KAN"),
    KAR("KAR", "Karen languages", "karen, langues", "Karenisch", "KS"),
    KAS("KAS", "Kashmiri", "kashmiri", "Kaschmiri", "KS"),
    KS("KS", "Kashmiri", "kashmiri", "Kaschmiri", "KAS"),
    GEO_1("GEO", "Georgian", "g\u00e9orgien", "Georgisch", "KA"),
    KAT_1("KAT", "Georgian", "g\u00e9orgien", "Georgisch", "KA"),
    KA_1("KA", "Georgian", "g\u00e9orgien", "Georgisch", "KAT"),
    KAU("KAU", "Kanuri", "kanouri", "Kanuri-Sprache", "KR"),
    KR("KR", "Kanuri", "kanouri", "Kanuri-Sprache", "KAU"),
    KAW("KAW", "kawi", "Kawi", "Kasachisch", "KAWI"),
    KAWI("KAWI", "kawi", "Kawi", "Kasachisch", "KAW"),
    KAZ("KAZ", "Kazakh", "kazakh", "Kasachisch", "KK"),
    KK("KK", "Kazakh", "kazakh", "Kasachisch", "KAZ"),
    KBD("KBD", "kabardien", "Kabardinisch", null, "KABARDIAN"),
    KABARDIAN("KABARDIAN", "kabardien", "Kabardinisch", null, "KBD"),
    KHA("KHA", "khasi", "Khasi-Sprache", "Khoisan-Sprachen (Andere)", "KHASI"),
    KHASI("KHASI", "khasi", "Khasi-Sprache", "Khoisan-Sprachen (Andere)", "KHA"),
    KHI("KHI", "Khoisan languages", "kho\u00efsan, langues", "Khoisan-Sprachen (Andere)", "KM"),
    KHM("KHM", "Central Khmer", "khmer central", "Kambodschanisch", "KM"),
    KM("KM", "Central Khmer", "khmer central", "Kambodschanisch", "KHM"),
    KHO("KHO", "Khotanese; Sakan", "khotanais; sakan", "Sakisch", "KI"),
    KIK("KIK", "Kikuyu; Gikuyu", "kikuyu", "Kikuyu-Sprache", "KI"),
    KI("KI", "Kikuyu; Gikuyu", "kikuyu", "Kikuyu-Sprache", "KIK"),
    KIN("KIN", "Kinyarwanda", "rwanda", "Rwanda-Sprache", "RW"),
    RW("RW", "Kinyarwanda", "rwanda", "Rwanda-Sprache", "KIN"),
    KIR("KIR", "Kirghiz; Kyrgyz", "kirghiz", "Kirgisisch", "KY"),
    KY("KY", "Kirghiz; Kyrgyz", "kirghiz", "Kirgisisch", "KIR"),
    KMB("KMB", "kimbundu", "Kimbundu-Sprache", null, "KIMBUNDU"),
    KIMBUNDU("KIMBUNDU", "kimbundu", "Kimbundu-Sprache", null, "KMB"),
    KOK("KOK", "konkani", "Konkani", "Komi-Sprache", "KONKANI"),
    KONKANI("KONKANI", "konkani", "Konkani", "Komi-Sprache", "KOK"),
    KOM("KOM", "Komi", "kom", "Komi-Sprache", "KV"),
    KV("KV", "Komi", "kom", "Komi-Sprache", "KOM"),
    KON("KON", "Kongo", "kongo", "Kongo-Sprache", "KG"),
    KG("KG", "Kongo", "kongo", "Kongo-Sprache", "KON"),
    KOR("KOR", "Korean", "cor\u00e9en", "Koreanisch", "KO"),
    KO("KO", "Korean", "cor\u00e9en", "Koreanisch", "KOR"),
    KOS("KOS", "kosrae", "Kosraeanisch", null, "KOSRAEAN"),
    KOSRAEAN("KOSRAEAN", "kosrae", "Kosraeanisch", null, "KOS"),
    KPE("KPE", "kpell\u00e9", "Kpelle-Sprache", null, "KPELLE"),
    KPELLE("KPELLE", "kpell\u00e9", "Kpelle-Sprache", null, "KPE"),
    KRC("KRC", "karatchai balkar", "Karatschaiisch-Balkarisch", null, "KARACHAY-BALKAR"),
    KARACHAY_BALKAR("KARACHAY-BALKAR", "karatchai balkar", "Karatschaiisch-Balkarisch", null, "KRC"),
    KRL("KRL", "car\u00e9lien", "Karelisch", "Kru-Sprachen (Andere)", "KARELIAN"),
    KARELIAN("KARELIAN", "car\u00e9lien", "Karelisch", "Kru-Sprachen (Andere)", "KRL"),
    KRO("KRO", "Kru languages", "krou, langues", "Kru-Sprachen (Andere)", "KURUKH"),
    KRU("KRU", "kurukh", "Oraon-Sprache", "Kwanyama-Sprache", "KURUKH"),
    KURUKH("KURUKH", "kurukh", "Oraon-Sprache", "Kwanyama-Sprache", "KRU"),
    KUA("KUA", "Kuanyama; Kwanyama", "kuanyama; kwanyama", "Kwanyama-Sprache", "KJ"),
    KJ("KJ", "Kuanyama; Kwanyama", "kuanyama; kwanyama", "Kwanyama-Sprache", "KUA"),
    KUM("KUM", "koumyk", "Kum\u00fckisch", "Kurdisch", "KUMYK"),
    KUMYK("KUMYK", "koumyk", "Kum\u00fckisch", "Kurdisch", "KUM"),
    KUR("KUR", "Kurdish", "kurde", "Kurdisch", "KU"),
    KU("KU", "Kurdish", "kurde", "Kurdisch", "KUR"),
    KUT("KUT", "kutenai", "Kutenai-Sprache", null, "KUTENAI"),
    KUTENAI("KUTENAI", "kutenai", "Kutenai-Sprache", null, "KUT"),
    LAD("LAD", "jud\u00e9o-espagnol", "Judenspanisch", null, "LADINO"),
    LADINO("LADINO", "jud\u00e9o-espagnol", "Judenspanisch", null, "LAD"),
    LAH("LAH", "lahnda", "Lahnda", null, "LAHNDA"),
    LAHNDA("LAHNDA", "lahnda", "Lahnda", null, "LAH"),
    LAM("LAM", "lamba", "Lamba-Sprache (Bantusprache)", "Laotisch", "LAMBA"),
    LAMBA("LAMBA", "lamba", "Lamba-Sprache (Bantusprache)", "Laotisch", "LAM"),
    LAO("LAO", "Lao", "lao", "Laotisch", "LO"),
    LO("LO", "Lao", "lao", "Laotisch", "LAO"),
    LAT("LAT", "Latin", "latin", "Latein", "LA"),
    LA("LA", "Latin", "latin", "Latein", "LAT"),
    LAV("LAV", "Latvian", "letton", "Lettisch", "LV"),
    LV("LV", "Latvian", "letton", "Lettisch", "LAV"),
    LEZ("LEZ", "lezghien", "Lesgisch", "Limburgisch", "LEZGHIAN"),
    LEZGHIAN("LEZGHIAN", "lezghien", "Lesgisch", "Limburgisch", "LEZ"),
    LIM("LIM", "Limburgan; Limburger; Limburgish", "limbourgeois", "Limburgisch", "LI"),
    LI("LI", "Limburgan; Limburger; Limburgish", "limbourgeois", "Limburgisch", "LIM"),
    LIN("LIN", "Lingala", "lingala", "Lingala", "LN"),
    LN("LN", "Lingala", "lingala", "Lingala", "LIN"),
    LIT("LIT", "Lithuanian", "lituanien", "Litauisch", "LT"),
    LT("LT", "Lithuanian", "lituanien", "Litauisch", "LIT"),
    LOL("LOL", "mongo", "Mongo-Sprache", null, "MONGO"),
    MONGO("MONGO", "mongo", "Mongo-Sprache", null, "LOL"),
    LOZ("LOZ", "lozi", "Rotse-Sprache", "Luxemburgisch", "LOZI"),
    LOZI("LOZI", "lozi", "Rotse-Sprache", "Luxemburgisch", "LOZ"),
    LTZ("LTZ", "Luxembourgish; Letzeburgesch", "luxembourgeois", "Luxemburgisch", "LB"),
    LB("LB", "Luxembourgish; Letzeburgesch", "luxembourgeois", "Luxemburgisch", "LTZ"),
    LUA("LUA", "luba-lulua", "Lulua-Sprache", "Luba-Katanga-Sprache", "LUBA-LULUA"),
    LUBA_LULUA("LUBA-LULUA", "luba-lulua", "Lulua-Sprache", "Luba-Katanga-Sprache", "LUA"),
    LUB("LUB", "Luba-Katanga", "luba-katanga", "Luba-Katanga-Sprache", "LU"),
    LU("LU", "Luba-Katanga", "luba-katanga", "Luba-Katanga-Sprache", "LUB"),
    LUG("LUG", "Ganda", "ganda", "Ganda-Sprache", "LG"),
    LG("LG", "Ganda", "ganda", "Ganda-Sprache", "LUG"),
    LUI("LUI", "luiseno", "Luise\u00f1o-Sprache", null, "LUISENO"),
    LUISENO("LUISENO", "luiseno", "Luise\u00f1o-Sprache", null, "LUI"),
    LUN("LUN", "lunda", "Lunda-Sprache", "Luo-Sprache", "LUNDA"),
    LUNDA("LUNDA", "lunda", "Lunda-Sprache", "Luo-Sprache", "LUN"),
    LUO("LUO", "Luo (Kenya and Tanzania)", "luo (Kenya et Tanzanie)", "Luo-Sprache", "LUSHAI"),
    LUS("LUS", "lushai", "Lushai-Sprache", null, "LUSHAI"),
    LUSHAI("LUSHAI", "lushai", "Lushai-Sprache", null, "LUS"),
    MAC("MAC", "Macedonian", "mac\u00e9donien", "Makedonisch", "MK"),
    MKD("MKD", "Macedonian", "mac\u00e9donien", "Makedonisch", "MK"),
    MK("MK", "Macedonian", "mac\u00e9donien", "Makedonisch", "MKD"),
    MAD("MAD", "madourais", "Maduresisch", null, "MADURESE"),
    MADURESE("MADURESE", "madourais", "Maduresisch", null, "MAD"),
    MAG("MAG", "magahi", "Khotta", "Marschallesisch", "MAGAHI"),
    MAGAHI("MAGAHI", "magahi", "Khotta", "Marschallesisch", "MAG"),
    MAH("MAH", "Marshallese", "marshall", "Marschallesisch", "MH"),
    MH("MH", "Marshallese", "marshall", "Marschallesisch", "MAH"),
    MAI("MAI", "maithili", "Maithili", null, "MAITHILI"),
    MAITHILI("MAITHILI", "maithili", "Maithili", null, "MAI"),
    MAK("MAK", "makassar", "Makassarisch", "Malayalam", "MAKASAR"),
    MAKASAR("MAKASAR", "makassar", "Makassarisch", "Malayalam", "MAK"),
    MAL("MAL", "Malayalam", "malayalam", "Malayalam", "ML"),
    ML("ML", "Malayalam", "malayalam", "Malayalam", "MAL"),
    MAN("MAN", "mandingue", "Malinke-Sprache", null, "MANDINGO"),
    MANDINGO("MANDINGO", "mandingue", "Malinke-Sprache", null, "MAN"),
    MAO("MAO", "Maori", "maori", "Maori-Sprache", "MI"),
    MRI("MRI", "Maori", "maori", "Maori-Sprache", "MI"),
    MI("MI", "Maori", "maori", "Maori-Sprache", "MRI"),
    MAP("MAP", "Austronesian languages", "austron\u00e9siennes, langues", "Austronesische Sprachen (Andere)", "MR"),
    MAR("MAR", "Marathi", "marathe", "Marathi", "MR"),
    MR("MR", "Marathi", "marathe", "Marathi", "MAR"),
    MAS("MAS", "massa\u00ef", "Massai-Sprache", null, "MASAI"),
    MASAI("MASAI", "massa\u00ef", "Massai-Sprache", null, "MAS"),
    MAY("MAY", "Malay", "malais", "Malaiisch", "MS"),
    MSA("MSA", "Malay", "malais", "Malaiisch", "MS"),
    MS("MS", "Malay", "malais", "Malaiisch", "MSA"),
    MDF("MDF", "moksa", "Mokscha-Sprache", null, "MOKSHA"),
    MOKSHA("MOKSHA", "moksa", "Mokscha-Sprache", null, "MDF"),
    MDR("MDR", "mandar", "Mandaresisch", null, "MANDAR"),
    MANDAR("MANDAR", "mandar", "Mandaresisch", null, "MDR"),
    MEN("MEN", "mend\u00e9", "Mende-Sprache", "Mittelirisch", "MENDE"),
    MENDE("MENDE", "mend\u00e9", "Mende-Sprache", "Mittelirisch", "MEN"),
    MGA("MGA", "Irish, Middle (900-1200)", "irlandais moyen (900-1200)", "Mittelirisch", null),
    MIC("MIC", "Mi'kmaq; Micmac", "mi'kmaq; micmac", "Micmac-Sprache", "MINANGKABAU"),
    MIN("MIN", "minangkabau", "Minangkabau-Sprache", "Einzelne andere Sprachen", "MINANGKABAU"),
    MINANGKABAU("MINANGKABAU", "minangkabau", "Minangkabau-Sprache", "Einzelne andere Sprachen", "MIN"),
    MIS("MIS", "Uncoded languages", "langues non cod\u00e9es", "Einzelne andere Sprachen", null),
    MAC_1("MAC", "Macedonian", "mac\u00e9donien", "Makedonisch", "MK"),
    MKD_1("MKD", "Macedonian", "mac\u00e9donien", "Makedonisch", "MK"),
    MK_1("MK", "Macedonian", "mac\u00e9donien", "Makedonisch", "MKD"),
    MKH("MKH", "Mon-Khmer languages", "m\u00f4n-khmer, langues", "Mon-Khmer-Sprachen (Andere)", "MG"),
    MLG("MLG", "Malagasy", "malgache", "Malagassi-Sprache", "MG"),
    MG("MG", "Malagasy", "malgache", "Malagassi-Sprache", "MLG"),
    MLT("MLT", "Maltese", "maltais", "Maltesisch", "MT"),
    MT("MT", "Maltese", "maltais", "Maltesisch", "MLT"),
    MNC("MNC", "mandchou", "Mandschurisch", null, "MANCHU"),
    MANCHU("MANCHU", "mandchou", "Mandschurisch", null, "MNC"),
    MNI("MNI", "manipuri", "Meithei-Sprache", "Manobo-Sprachen", "MANIPURI"),
    MANIPURI("MANIPURI", "manipuri", "Meithei-Sprache", "Manobo-Sprachen", "MNI"),
    MNO("MNO", "Manobo languages", "manobo, langues", "Manobo-Sprachen", "MOHAWK"),
    MOH("MOH", "mohawk", "Mohawk-Sprache", "Mongolisch", "MOHAWK"),
    MOHAWK("MOHAWK", "mohawk", "Mohawk-Sprache", "Mongolisch", "MOH"),
    MON("MON", "Mongolian", "mongol", "Mongolisch", "MN"),
    MN("MN", "Mongolian", "mongol", "Mongolisch", "MON"),
    MOS("MOS", "mor\u00e9", "Mossi-Sprache", null, "MOSSI"),
    MOSSI("MOSSI", "mor\u00e9", "Mossi-Sprache", null, "MOS"),
    MAO_1("MAO", "Maori", "maori", "Maori-Sprache", "MI"),
    MRI_1("MRI", "Maori", "maori", "Maori-Sprache", "MI"),
    MI_1("MI", "Maori", "maori", "Maori-Sprache", "MRI"),
    MAY_1("MAY", "Malay", "malais", "Malaiisch", "MS"),
    MSA_1("MSA", "Malay", "malais", "Malaiisch", "MS"),
    MS_1("MS", "Malay", "malais", "Malaiisch", "MSA"),
    MUL("MUL", "Multiple languages", "multilingue", "Mehrere Sprachen", null),
    MUN("MUN", "Munda languages", "mounda, langues", "Mundasprachen (Andere)", "CREEK"),
    MUS("MUS", "muskogee", "Muskogisch", null, "CREEK"),
    CREEK("CREEK", "muskogee", "Muskogisch", null, "MUS"),
    MWL("MWL", "mirandais", "Mirandesisch", null, "MIRANDESE"),
    MIRANDESE("MIRANDESE", "mirandais", "Mirandesisch", null, "MWL"),
    MWR("MWR", "marvari", "Marwari", null, "MARWARI"),
    MARWARI("MARWARI", "marvari", "Marwari", null, "MWR"),
    BUR_1("BUR", "Burmese", "birman", "Birmanisch", "MY"),
    MYA_1("MYA", "Burmese", "birman", "Birmanisch", "MY"),
    MY_1("MY", "Burmese", "birman", "Birmanisch", "MYA"),
    MYN("MYN", "Mayan languages", "maya, langues", "Maya-Sprachen", "ERZYA"),
    MYV("MYV", "erza", "Erza-Mordwinisch", "Nahuatl", "ERZYA"),
    ERZYA("ERZYA", "erza", "Erza-Mordwinisch", "Nahuatl", "MYV"),
    NAH("NAH", "Nahuatl languages", "nahuatl, langues", "Nahuatl", null),
    NAI("NAI", "North American Indian languages", "nord-am\u00e9rindiennes, langues", "Indianersprachen, Nordamerika (Andere)", "NEAPOLITAN"),
    NAP("NAP", "napolitain", "Neapel / Mundart", "Nauruanisch", "NEAPOLITAN"),
    NEAPOLITAN("NEAPOLITAN", "napolitain", "Neapel / Mundart", "Nauruanisch", "NAP"),
    NAU("NAU", "Nauru", "nauruan", "Nauruanisch", "NA"),
    NA("NA", "Nauru", "nauruan", "Nauruanisch", "NAU"),
    NAV("NAV", "Navajo; Navaho", "navaho", "Navajo-Sprache", "NV"),
    NV("NV", "Navajo; Navaho", "navaho", "Navajo-Sprache", "NAV"),
    NBL("NBL", "Ndebele, South; South Ndebele", "nd\u00e9b\u00e9l\u00e9 du Sud", "Ndebele-Sprache (Transvaal)", "NR"),
    NR("NR", "Ndebele, South; South Ndebele", "nd\u00e9b\u00e9l\u00e9 du Sud", "Ndebele-Sprache (Transvaal)", "NBL"),
    NDE("NDE", "Ndebele, North; North Ndebele", "nd\u00e9b\u00e9l\u00e9 du Nord", "Ndebele-Sprache (Simbabwe)", "ND"),
    ND("ND", "Ndebele, North; North Ndebele", "nd\u00e9b\u00e9l\u00e9 du Nord", "Ndebele-Sprache (Simbabwe)", "NDE"),
    NDO("NDO", "Ndonga", "ndonga", "Ndonga", "NG"),
    NG("NG", "Ndonga", "ndonga", "Ndonga", "NDO"),
    NDS("NDS", "Low German; Low Saxon; German, Low; Saxon, Low", "bas allemand; bas saxon; allemand, bas; saxon, bas", "Niederdeutsch", "NE"),
    NEP("NEP", "Nepali", "n\u00e9palais", "Nepali", "NE"),
    NE("NE", "Nepali", "n\u00e9palais", "Nepali", "NEP"),
    NEW("NEW", "Nepal Bhasa; Newari", "nepal bhasa; newari", "Newari", "NIAS"),
    NIA("NIA", "nias", "Nias-Sprache", "Nigerkordofanische Sprachen (Andere)", "NIAS"),
    NIAS("NIAS", "nias", "Nias-Sprache", "Nigerkordofanische Sprachen (Andere)", "NIA"),
    NIC("NIC", "Niger-Kordofanian languages", "nig\u00e9ro-kordofaniennes, langues", "Nigerkordofanische Sprachen (Andere)", "NIUEAN"),
    NIU("NIU", "niu\u00e9", "Niue-Sprache", null, "NIUEAN"),
    NIUEAN("NIUEAN", "niu\u00e9", "Niue-Sprache", null, "NIU"),
    DUT_1("DUT", "Dutch; Flemish", "n\u00e9erlandais; flamand", "Niederl\u00e4ndisch", "NL"),
    NLD_1("NLD", "Dutch; Flemish", "n\u00e9erlandais; flamand", "Niederl\u00e4ndisch", "NL"),
    NL_1("NL", "Dutch; Flemish", "n\u00e9erlandais; flamand", "Niederl\u00e4ndisch", "NLD"),
    NNO("NNO", "Norwegian Nynorsk; Nynorsk, Norwegian", "norv\u00e9gien nynorsk; nynorsk, norv\u00e9gien", "Nynorsk", "NN"),
    NN("NN", "Norwegian Nynorsk; Nynorsk, Norwegian", "norv\u00e9gien nynorsk; nynorsk, norv\u00e9gien", "Nynorsk", "NNO"),
    NOB("NOB", "Bokm\u00e5l, Norwegian; Norwegian Bokm\u00e5l", "norv\u00e9gien bokm\u00e5l", "Bokm\u00e5l", "NB"),
    NB("NB", "Bokm\u00e5l, Norwegian; Norwegian Bokm\u00e5l", "norv\u00e9gien bokm\u00e5l", "Bokm\u00e5l", "NOB"),
    NOG("NOG", "noga\u00ef; nogay", "Nogaisch", "Altnorwegisch", "NOGAI"),
    NOGAI("NOGAI", "noga\u00ef; nogay", "Nogaisch", "Altnorwegisch", "NOG"),
    NON("NON", "Norse, Old", "norrois, vieux", "Altnorwegisch", "NO"),
    NOR("NOR", "Norwegian", "norv\u00e9gien", "Norwegisch", "NO"),
    NO("NO", "Norwegian", "norv\u00e9gien", "Norwegisch", "NOR"),
    NQO("NQO", "n'ko", "N'Ko", "Pedi-Sprache", "N'KO"),
    N_KO("N'KO", "n'ko", "N'Ko", "Pedi-Sprache", "NQO"),
    NSO("NSO", "Pedi; Sepedi; Northern Sotho", "pedi; sepedi; sotho du Nord", "Pedi-Sprache", null),
    NUB("NUB", "Nubian languages", "nubiennes, langues", "Nubische Sprachen", null),
    NWC("NWC", "Classical Newari; Old Newari; Classical Nepal Bhasa", "newari classique", "Alt-Newari", "NY"),
    NYA("NYA", "Chichewa; Chewa; Nyanja", "chichewa; chewa; nyanja", "Nyanja-Sprache", "NY"),
    NY("NY", "Chichewa; Chewa; Nyanja", "chichewa; chewa; nyanja", "Nyanja-Sprache", "NYA"),
    NYM("NYM", "nyamwezi", "Nyamwezi-Sprache", null, "NYAMWEZI"),
    NYAMWEZI("NYAMWEZI", "nyamwezi", "Nyamwezi-Sprache", null, "NYM"),
    NYN("NYN", "nyankol\u00e9", "Nkole-Sprache", null, "NYANKOLE"),
    NYANKOLE("NYANKOLE", "nyankol\u00e9", "Nkole-Sprache", null, "NYN"),
    NYO("NYO", "nyoro", "Nyoro-Sprache", null, "NYORO"),
    NYORO("NYORO", "nyoro", "Nyoro-Sprache", null, "NYO"),
    NZI("NZI", "nzema", "Nzima-Sprache", "Okzitanisch", "NZIMA"),
    NZIMA("NZIMA", "nzema", "Nzima-Sprache", "Okzitanisch", "NZI"),
    OCI("OCI", "Occitan (post 1500)", "occitan (apr\u00e8s 1500)", "Okzitanisch", "OC"),
    OC("OC", "Occitan (post 1500)", "occitan (apr\u00e8s 1500)", "Okzitanisch", "OCI"),
    OJI("OJI", "Ojibwa", "ojibwa", "Ojibwa-Sprache", "OJ"),
    OJ("OJ", "Ojibwa", "ojibwa", "Ojibwa-Sprache", "OJI"),
    ORI("ORI", "Oriya", "oriya", "Oriya-Sprache", "OR"),
    OR("OR", "Oriya", "oriya", "Oriya-Sprache", "ORI"),
    ORM("ORM", "Oromo", "galla", "Galla-Sprache", "OM"),
    OM("OM", "Oromo", "galla", "Galla-Sprache", "ORM"),
    OSA("OSA", "osage", "Osage-Sprache", "Ossetisch", "OSAGE"),
    OSAGE("OSAGE", "osage", "Osage-Sprache", "Ossetisch", "OSA"),
    OSS("OSS", "Ossetian; Ossetic", "oss\u00e8te", "Ossetisch", "OS"),
    OS("OS", "Ossetian; Ossetic", "oss\u00e8te", "Ossetisch", "OSS"),
    OTA("OTA", "Turkish, Ottoman (1500-1928)", "turc ottoman (1500-1928)", "Osmanisch", null),
    OTO("OTO", "Otomian languages", "otomi, langues", "Otomangue-Sprachen", null),
    PAA("PAA", "Papuan languages", "papoues, langues", "Papuasprachen (Andere)", "PANGASINAN"),
    PAG("PAG", "pangasinan", "Pangasinan-Sprache", null, "PANGASINAN"),
    PANGASINAN("PANGASINAN", "pangasinan", "Pangasinan-Sprache", null, "PAG"),
    PAL("PAL", "pahlavi", "Mittelpersisch", "Pampanggan-Sprache", "PAHLAVI"),
    PAHLAVI("PAHLAVI", "pahlavi", "Mittelpersisch", "Pampanggan-Sprache", "PAL"),
    PAM("PAM", "Pampanga; Kapampangan", "pampangan", "Pampanggan-Sprache", "PA"),
    PAN("PAN", "Panjabi; Punjabi", "pendjabi", "Pandschabi-Sprache", "PA"),
    PA("PA", "Panjabi; Punjabi", "pendjabi", "Pandschabi-Sprache", "PAN"),
    PAP("PAP", "papiamento", "Papiamento", null, "PAPIAMENTO"),
    PAPIAMENTO("PAPIAMENTO", "papiamento", "Papiamento", null, "PAP"),
    PAU("PAU", "palau", "Palau-Sprache", "Altpersisch", "PALAUAN"),
    PALAUAN("PALAUAN", "palau", "Palau-Sprache", "Altpersisch", "PAU"),
    PEO("PEO", "Persian, Old (ca.600-400 B.C.)", "perse, vieux (ca. 600-400 av. J.-C.)", "Altpersisch", null),
    PER_1("PER", "Persian", "persan", "Persisch", "FA"),
    FAS_1("FAS", "Persian", "persan", "Persisch", "FA"),
    FA_1("FA", "Persian", "persan", "Persisch", "FAS"),
    PHI("PHI", "Philippine languages", "philippines, langues", "Philippinisch-Austronesisch (Andere)", "PHOENICIAN"),
    PHN("PHN", "ph\u00e9nicien", "Ph\u00f6nikisch", "Pali", "PHOENICIAN"),
    PHOENICIAN("PHOENICIAN", "ph\u00e9nicien", "Ph\u00f6nikisch", "Pali", "PHN"),
    PLI("PLI", "Pali", "pali", "Pali", "PI"),
    PI("PI", "Pali", "pali", "Pali", "PLI"),
    POL("POL", "Polish", "polonais", "Polnisch", "PL"),
    PL("PL", "Polish", "polonais", "Polnisch", "POL"),
    PON("PON", "pohnpei", "Ponapeanisch", "Portugiesisch", "POHNPEIAN"),
    POHNPEIAN("POHNPEIAN", "pohnpei", "Ponapeanisch", "Portugiesisch", "PON"),
    POR("POR", "Portuguese", "portugais", "Portugiesisch", "PT"),
    PT("PT", "Portuguese", "portugais", "Portugiesisch", "POR"),
    PRA("PRA", "Prakrit languages", "pr\u00e2krit, langues", "Prakrit", null),
    PRO("PRO", "Proven\u00e7al, Old (to 1500);Occitan, Old (to 1500)", "proven\u00e7al ancien (jusqu'\u00e0 1500); occitan ancien (jusqu'\u00e0 1500)", "Altokzitanisch", "PS"),
    PUS("PUS", "Pushto; Pashto", "pachto", "Paschtu", "PS"),
    PS("PS", "Pushto; Pashto", "pachto", "Paschtu", "PUS"),
    QAA_QTZ("QAA-QTZ", "Reserved for local use", "r\u00e9serv\u00e9e \u00e0 l'usage local", "Reserviert f\u00fcr lokale Verwendung", "QU"),
    QUE("QUE", "Quechua", "quechua", "Quechua-Sprache", "QU"),
    QU("QU", "Quechua", "quechua", "Quechua-Sprache", "QUE"),
    RAJ("RAJ", "rajasthani", "Rajasthani", null, "RAJASTHANI"),
    RAJASTHANI("RAJASTHANI", "rajasthani", "Rajasthani", null, "RAJ"),
    RAP("RAP", "rapanui", "Osterinsel-Sprache", "Rarotonganisch", "RAPANUI"),
    RAPANUI("RAPANUI", "rapanui", "Osterinsel-Sprache", "Rarotonganisch", "RAP"),
    RAR("RAR", "Rarotongan; Cook Islands Maori", "rarotonga; maori des \u00eeles Cook", "Rarotonganisch", null),
    ROA("ROA", "Romance languages", "romanes, langues", "Romanische Sprachen (Andere)", "RM"),
    ROH("ROH", "Romansh", "romanche", "R\u00e4toromanisch", "RM"),
    RM("RM", "Romansh", "romanche", "R\u00e4toromanisch", "ROH"),
    ROM("ROM", "tsigane", "Romani (Sprache)", null, "ROMANY"),
    ROMANY("ROMANY", "tsigane", "Romani (Sprache)", null, "ROM"),
    RUM("RUM", "Romanian; Moldavian; Moldovan", "roumain; moldave", "Rum\u00e4nisch", "RO"),
    RON("RON", "Romanian; Moldavian; Moldovan", "roumain; moldave", "Rum\u00e4nisch", "RO"),
    RO("RO", "Romanian; Moldavian; Moldovan", "roumain; moldave", "Rum\u00e4nisch", "RON"),
    RUM_1("RUM", "Romanian; Moldavian; Moldovan", "roumain; moldave", "Rum\u00e4nisch", "RO"),
    RON_1("RON", "Romanian; Moldavian; Moldovan", "roumain; moldave", "Rum\u00e4nisch", "RO"),
    RO_1("RO", "Romanian; Moldavian; Moldovan", "roumain; moldave", "Rum\u00e4nisch", "RON"),
    RUN("RUN", "Rundi", "rundi", "Rundi-Sprache", "RN"),
    RN("RN", "Rundi", "rundi", "Rundi-Sprache", "RUN"),
    RUP("RUP", "Aromanian; Arumanian; Macedo-Romanian", "aroumain; mac\u00e9do-roumain", "Aromunisch", "RU"),
    RUS("RUS", "Russian", "russe", "Russisch", "RU"),
    RU("RU", "Russian", "russe", "Russisch", "RUS"),
    SAD("SAD", "sandawe", "Sandawe-Sprache", "Sango-Sprache", "SANDAWE"),
    SANDAWE("SANDAWE", "sandawe", "Sandawe-Sprache", "Sango-Sprache", "SAD"),
    SAG("SAG", "Sango", "sango", "Sango-Sprache", "SG"),
    SG("SG", "Sango", "sango", "Sango-Sprache", "SAG"),
    SAH("SAH", "iakoute", "Jakutisch", "Indianersprachen, S\u00fcdamerika (Andere)", "YAKUT"),
    YAKUT("YAKUT", "iakoute", "Jakutisch", "Indianersprachen, S\u00fcdamerika (Andere)", "SAH"),
    SAI("SAI", "South American Indian languages", "sud-am\u00e9rindiennes, langues", "Indianersprachen, S\u00fcdamerika (Andere)", null),
    SAL("SAL", "Salishan languages", "salishennes, langues", "Salish-Sprache", null),
    SAM("SAM", "Samaritan Aramaic", "samaritain", "Samaritanisch", "SA"),
    SAN("SAN", "Sanskrit", "sanskrit", "Sanskrit", "SA"),
    SA("SA", "Sanskrit", "sanskrit", "Sanskrit", "SAN"),
    SAS("SAS", "sasak", "Sasak", null, "SASAK"),
    SASAK("SASAK", "sasak", "Sasak", null, "SAS"),
    SAT("SAT", "santal", "Santali", null, "SANTALI"),
    SANTALI("SANTALI", "santal", "Santali", null, "SAT"),
    SCN("SCN", "sicilien", "Sizilianisch", null, "SICILIAN"),
    SICILIAN("SICILIAN", "sicilien", "Sizilianisch", null, "SCN"),
    SCO("SCO", "\u00e9cossais", "Schottisch", null, "SCOTS"),
    SCOTS("SCOTS", "\u00e9cossais", "Schottisch", null, "SCO"),
    SEL("SEL", "selkoupe", "Selkupisch", "Semitische Sprachen (Andere)", "SELKUP"),
    SELKUP("SELKUP", "selkoupe", "Selkupisch", "Semitische Sprachen (Andere)", "SEL"),
    SEM("SEM", "Semitic languages", "s\u00e9mitiques, langues", "Semitische Sprachen (Andere)", null),
    SGA("SGA", "Irish, Old (to 900)", "irlandais ancien (jusqu'\u00e0 900)", "Altirisch", null),
    SGN("SGN", "Sign Languages", "langues des signes", "Zeichensprachen", "SHAN"),
    SHN("SHN", "chan", "Schan-Sprache", null, "SHAN"),
    SHAN("SHAN", "chan", "Schan-Sprache", null, "SHN"),
    SID("SID", "sidamo", "Sidamo-Sprache", "Singhalesisch", "SIDAMO"),
    SIDAMO("SIDAMO", "sidamo", "Sidamo-Sprache", "Singhalesisch", "SID"),
    SIN("SIN", "Sinhala; Sinhalese", "singhalais", "Singhalesisch", "SI"),
    SI("SI", "Sinhala; Sinhalese", "singhalais", "Singhalesisch", "SIN"),
    SIO("SIO", "Siouan languages", "sioux, langues", "Sioux-Sprachen (Andere)", null),
    SIT("SIT", "Sino-Tibetan languages", "sino-tib\u00e9taines, langues", "Sinotibetische Sprachen (Andere)", null),
    SLA("SLA", "Slavic languages", "slaves, langues", "Slawische Sprachen (Andere)", null),
    SLO("SLO", "Slovak", "slovaque", "Slowakisch", "SK"),
    SLK("SLK", "Slovak", "slovaque", "Slowakisch", "SK"),
    SK("SK", "Slovak", "slovaque", "Slowakisch", "SLK"),
    SLO_1("SLO", "Slovak", "slovaque", "Slowakisch", "SK"),
    SLK_1("SLK", "Slovak", "slovaque", "Slowakisch", "SK"),
    SK_1("SK", "Slovak", "slovaque", "Slowakisch", "SLK"),
    SLV("SLV", "Slovenian", "slov\u00e8ne", "Slowenisch", "SL"),
    SL("SL", "Slovenian", "slov\u00e8ne", "Slowenisch", "SLV"),
    SMA("SMA", "Southern Sami", "sami du Sud", "S\u00fcdsaamisch", "SE"),
    SME("SME", "Northern Sami", "sami du Nord", "Nordsaamisch", "SE"),
    SE("SE", "Northern Sami", "sami du Nord", "Nordsaamisch", "SME"),
    SMI("SMI", "Sami languages", "sames, langues", "Saamisch", null),
    SMJ("SMJ", "Lule Sami", "sami de Lule", "Lulesaamisch", null),
    SMN("SMN", "Inari Sami", "sami d'Inari", "Inarisaamisch", "SM"),
    SMO("SMO", "Samoan", "samoan", "Samoanisch", "SM"),
    SM("SM", "Samoan", "samoan", "Samoanisch", "SMO"),
    SMS("SMS", "Skolt Sami", "sami skolt", "Skoltsaamisch", "SN"),
    SNA("SNA", "Shona", "shona", "Schona-Sprache", "SN"),
    SN("SN", "Shona", "shona", "Schona-Sprache", "SNA"),
    SND("SND", "Sindhi", "sindhi", "Sindhi-Sprache", "SD"),
    SD("SD", "Sindhi", "sindhi", "Sindhi-Sprache", "SND"),
    SNK("SNK", "sonink\u00e9", "Soninke-Sprache", null, "SONINKE"),
    SONINKE("SONINKE", "sonink\u00e9", "Soninke-Sprache", null, "SNK"),
    SOG("SOG", "sogdien", "Sogdisch", "Somali", "SOGDIAN"),
    SOGDIAN("SOGDIAN", "sogdien", "Sogdisch", "Somali", "SOG"),
    SOM("SOM", "Somali", "somali", "Somali", "SO"),
    SO("SO", "Somali", "somali", "Somali", "SOM"),
    SON("SON", "Songhai languages", "songhai, langues", "Songhai-Sprache", "ST"),
    SOT("SOT", "Sotho, Southern", "sotho du Sud", "S\u00fcd-Sotho-Sprache", "ST"),
    ST("ST", "Sotho, Southern", "sotho du Sud", "S\u00fcd-Sotho-Sprache", "SOT"),
    SPA("SPA", "Spanish; Castilian", "espagnol; castillan", "Spanisch", "ES"),
    ES("ES", "Spanish; Castilian", "espagnol; castillan", "Spanisch", "SPA"),
    ALB_1("ALB", "Albanian", "albanais", "Albanisch", "SQ"),
    SQI_1("SQI", "Albanian", "albanais", "Albanisch", "SQ"),
    SQ_1("SQ", "Albanian", "albanais", "Albanisch", "SQI"),
    SRD("SRD", "Sardinian", "sarde", "Sardisch", "SC"),
    SC("SC", "Sardinian", "sarde", "Sardisch", "SRD"),
    SRN("SRN", "Sranan Tongo", "sranan tongo", "Sranantongo", "SR"),
    SRP("SRP", "Serbian", "serbe", "Serbisch", "SR"),
    SR("SR", "Serbian", "serbe", "Serbisch", "SRP"),
    SRR("SRR", "s\u00e9r\u00e8re", "Serer-Sprache", "Nilosaharanische Sprachen (Andere)", "SERER"),
    SERER("SERER", "s\u00e9r\u00e8re", "Serer-Sprache", "Nilosaharanische Sprachen (Andere)", "SRR"),
    SSA("SSA", "Nilo-Saharan languages", "nilo-sahariennes, langues", "Nilosaharanische Sprachen (Andere)", "SS"),
    SSW("SSW", "Swati", "swati", "Swasi-Sprache", "SS"),
    SS("SS", "Swati", "swati", "Swasi-Sprache", "SSW"),
    SUK("SUK", "sukuma", "Sukuma-Sprache", "Sundanesisch", "SUKUMA"),
    SUKUMA("SUKUMA", "sukuma", "Sukuma-Sprache", "Sundanesisch", "SUK"),
    SUN("SUN", "Sundanese", "soundanais", "Sundanesisch", "SU"),
    SU("SU", "Sundanese", "soundanais", "Sundanesisch", "SUN"),
    SUS("SUS", "soussou", "Susu", null, "SUSU"),
    SUSU("SUSU", "soussou", "Susu", null, "SUS"),
    SUX("SUX", "sum\u00e9rien", "Sumerisch", "Swahili", "SUMERIAN"),
    SUMERIAN("SUMERIAN", "sum\u00e9rien", "Sumerisch", "Swahili", "SUX"),
    SWA("SWA", "Swahili", "swahili", "Swahili", "SW"),
    SW("SW", "Swahili", "swahili", "Swahili", "SWA"),
    SWE("SWE", "Swedish", "su\u00e9dois", "Schwedisch", "SV"),
    SV("SV", "Swedish", "su\u00e9dois", "Schwedisch", "SWE"),
    SYC("SYC", "Classical Syriac", "syriaque classique", "Syrisch", "SYRIAC"),
    SYR("SYR", "syriaque", "Neuostaram\u00e4isch", "Tahitisch", "SYRIAC"),
    SYRIAC("SYRIAC", "syriaque", "Neuostaram\u00e4isch", "Tahitisch", "SYR"),
    TAH("TAH", "Tahitian", "tahitien", "Tahitisch", "TY"),
    TY("TY", "Tahitian", "tahitien", "Tahitisch", "TAH"),
    TAI("TAI", "Tai languages", "tai, langues", "Thaisprachen (Andere)", "TA"),
    TAM("TAM", "Tamil", "tamoul", "Tamil", "TA"),
    TA("TA", "Tamil", "tamoul", "Tamil", "TAM"),
    TAT("TAT", "Tatar", "tatar", "Tatarisch", "TT"),
    TT("TT", "Tatar", "tatar", "Tatarisch", "TAT"),
    TEL("TEL", "Telugu", "t\u00e9lougou", "Telugu-Sprache", "TE"),
    TE("TE", "Telugu", "t\u00e9lougou", "Telugu-Sprache", "TEL"),
    TEM("TEM", "temne", "Temne-Sprache", null, "TIMNE"),
    TIMNE("TIMNE", "temne", "Temne-Sprache", null, "TEM"),
    TER("TER", "tereno", "Tereno-Sprache", null, "TERENO"),
    TERENO("TERENO", "tereno", "Tereno-Sprache", null, "TER"),
    TET("TET", "tetum", "Tetum-Sprache", "Tadschikisch", "TETUM"),
    TETUM("TETUM", "tetum", "Tetum-Sprache", "Tadschikisch", "TET"),
    TGK("TGK", "Tajik", "tadjik", "Tadschikisch", "TG"),
    TG("TG", "Tajik", "tadjik", "Tadschikisch", "TGK"),
    TGL("TGL", "Tagalog", "tagalog", "Tagalog", "TL"),
    TL("TL", "Tagalog", "tagalog", "Tagalog", "TGL"),
    THA("THA", "Thai", "tha\u00ef", "Thail\u00e4ndisch", "TH"),
    TH("TH", "Thai", "tha\u00ef", "Thail\u00e4ndisch", "THA"),
    TIB_1("TIB", "Tibetan", "tib\u00e9tain", "Tibetisch", "BO"),
    BOD_1("BOD", "Tibetan", "tib\u00e9tain", "Tibetisch", "BO"),
    BO_1("BO", "Tibetan", "tib\u00e9tain", "Tibetisch", "BOD"),
    TIG("TIG", "tigr\u00e9", "Tigre-Sprache", "Tigrinja-Sprache", "TIGRE"),
    TIGRE("TIGRE", "tigr\u00e9", "Tigre-Sprache", "Tigrinja-Sprache", "TIG"),
    TIR("TIR", "Tigrinya", "tigrigna", "Tigrinja-Sprache", "TI"),
    TI("TI", "Tigrinya", "tigrigna", "Tigrinja-Sprache", "TIR"),
    TIV("TIV", "tiv", "Tiv-Sprache", null, "TIV"),
    TIV_1("TIV", "tiv", "Tiv-Sprache", null, "TIV"),
    TKL("TKL", "tokelau", "Tokelauanisch", "Klingonisch", "TOKELAU"),
    TOKELAU("TOKELAU", "tokelau", "Tokelauanisch", "Klingonisch", "TKL"),
    TLH("TLH", "Klingon; tlhIngan-Hol", "klingon", "Klingonisch", "TLINGIT"),
    TLI("TLI", "tlingit", "Tlingit-Sprache", null, "TLINGIT"),
    TLINGIT("TLINGIT", "tlingit", "Tlingit-Sprache", null, "TLI"),
    TMH("TMH", "tamacheq", "Tama\u0161eq", "Tonga (Bantusprache, Sambia)", "TAMASHEK"),
    TAMASHEK("TAMASHEK", "tamacheq", "Tama\u0161eq", "Tonga (Bantusprache, Sambia)", "TMH"),
    TOG("TOG", "Tonga (Nyasa)", "tonga (Nyasa)", "Tonga (Bantusprache, Sambia)", "TO"),
    TON("TON", "Tonga (Tonga Islands)", "tongan (\u00celes Tonga)", "Tongaisch", "TO"),
    TO("TO", "Tonga (Tonga Islands)", "tongan (\u00celes Tonga)", "Tongaisch", "TON"),
    TPI("TPI", "Tok Pisin", "tok pisin", "Neumelanesisch", "TSIMSHIAN"),
    TSI("TSI", "tsimshian", "Tsimshian-Sprache", "Tswana-Sprache", "TSIMSHIAN"),
    TSIMSHIAN("TSIMSHIAN", "tsimshian", "Tsimshian-Sprache", "Tswana-Sprache", "TSI"),
    TSN("TSN", "Tswana", "tswana", "Tswana-Sprache", "TN"),
    TN("TN", "Tswana", "tswana", "Tswana-Sprache", "TSN"),
    TSO("TSO", "Tsonga", "tsonga", "Tsonga-Sprache", "TS"),
    TS("TS", "Tsonga", "tsonga", "Tsonga-Sprache", "TSO"),
    TUK("TUK", "Turkmen", "turkm\u00e8ne", "Turkmenisch", "TK"),
    TK("TK", "Turkmen", "turkm\u00e8ne", "Turkmenisch", "TUK"),
    TUM("TUM", "tumbuka", "Tumbuka-Sprache", "Tupi-Sprache", "TUMBUKA"),
    TUMBUKA("TUMBUKA", "tumbuka", "Tumbuka-Sprache", "Tupi-Sprache", "TUM"),
    TUP("TUP", "Tupi languages", "tupi, langues", "Tupi-Sprache", "TR"),
    TUR("TUR", "Turkish", "turc", "T\u00fcrkisch", "TR"),
    TR("TR", "Turkish", "turc", "T\u00fcrkisch", "TUR"),
    TUT("TUT", "Altaic languages", "alta\u00efques, langues", "Altaische Sprachen (Andere)", "TUVALU"),
    TVL("TVL", "tuvalu", "Elliceanisch", "Twi-Sprache", "TUVALU"),
    TUVALU("TUVALU", "tuvalu", "Elliceanisch", "Twi-Sprache", "TVL"),
    TWI("TWI", "Twi", "twi", "Twi-Sprache", "TW"),
    TW("TW", "Twi", "twi", "Twi-Sprache", "TWI"),
    TYV("TYV", "touva", "Tuwinisch", null, "TUVINIAN"),
    TUVINIAN("TUVINIAN", "touva", "Tuwinisch", null, "TYV"),
    UDM("UDM", "oudmourte", "Udmurtisch", null, "UDMURT"),
    UDMURT("UDMURT", "oudmourte", "Udmurtisch", null, "UDM"),
    UGA("UGA", "ougaritique", "Ugaritisch", "Uigurisch", "UGARITIC"),
    UGARITIC("UGARITIC", "ougaritique", "Ugaritisch", "Uigurisch", "UGA"),
    UIG("UIG", "Uighur; Uyghur", "ou\u00efgour", "Uigurisch", "UG"),
    UG("UG", "Uighur; Uyghur", "ou\u00efgour", "Uigurisch", "UIG"),
    UKR("UKR", "Ukrainian", "ukrainien", "Ukrainisch", "UK"),
    UK("UK", "Ukrainian", "ukrainien", "Ukrainisch", "UKR"),
    UMB("UMB", "umbundu", "Mbundu-Sprache", null, "UMBUNDU"),
    UMBUNDU("UMBUNDU", "umbundu", "Mbundu-Sprache", null, "UMB"),
    UND("UND", "ind\u00e9termin\u00e9e", "Nicht zu entscheiden", "Urdu", "UNDETERMINED"),
    UNDETERMINED("UNDETERMINED", "ind\u00e9termin\u00e9e", "Nicht zu entscheiden", "Urdu", "UND"),
    URD("URD", "Urdu", "ourdou", "Urdu", "UR"),
    UR("UR", "Urdu", "ourdou", "Urdu", "URD"),
    UZB("UZB", "Uzbek", "ouszbek", "Usbekisch", "UZ"),
    UZ("UZ", "Uzbek", "ouszbek", "Usbekisch", "UZB"),
    VAI("VAI", "va\u00ef", "Vai-Sprache", "Venda-Sprache", "VAI"),
    VAI_1("VAI", "va\u00ef", "Vai-Sprache", "Venda-Sprache", "VAI"),
    VEN("VEN", "Venda", "venda", "Venda-Sprache", "VE"),
    VE("VE", "Venda", "venda", "Venda-Sprache", "VEN"),
    VIE("VIE", "Vietnamese", "vietnamien", "Vietnamesisch", "VI"),
    VI("VI", "Vietnamese", "vietnamien", "Vietnamesisch", "VIE"),
    VOL("VOL", "Volap\u00fck", "volap\u00fck", "Volap\u00fck", "VO"),
    VO("VO", "Volap\u00fck", "volap\u00fck", "Volap\u00fck", "VOL"),
    VOT("VOT", "vote", "Wotisch", "Wakash-Sprachen", "VOTIC"),
    VOTIC("VOTIC", "vote", "Wotisch", "Wakash-Sprachen", "VOT"),
    WAK("WAK", "Wakashan languages", "wakashanes, langues", "Wakash-Sprachen", null),
    WAL("WAL", "Wolaitta; Wolaytta", "wolaitta; wolaytta", "Walamo-Sprache", "WARAY"),
    WAR("WAR", "waray", "Waray", null, "WARAY"),
    WARAY("WARAY", "waray", "Waray", null, "WAR"),
    WAS("WAS", "washo", "Washo-Sprache", null, "WASHO"),
    WASHO("WASHO", "washo", "Washo-Sprache", null, "WAS"),
    WEL_1("WEL", "Welsh", "gallois", "Kymrisch", "CY"),
    CYM_1("CYM", "Welsh", "gallois", "Kymrisch", "CY"),
    CY_1("CY", "Welsh", "gallois", "Kymrisch", "CYM"),
    WEN("WEN", "Sorbian languages", "sorabes, langues", "Sorbisch (Andere)", "WA"),
    WLN("WLN", "Walloon", "wallon", "Wallonisch", "WA"),
    WA("WA", "Walloon", "wallon", "Wallonisch", "WLN"),
    WOL("WOL", "Wolof", "wolof", "Wolof-Sprache", "WO"),
    WO("WO", "Wolof", "wolof", "Wolof-Sprache", "WOL"),
    XAL("XAL", "Kalmyk; Oirat", "kalmouk; o\u00efrat", "Kalm\u00fcckisch", "XH"),
    XHO("XHO", "Xhosa", "xhosa", "Xhosa-Sprache", "XH"),
    XH("XH", "Xhosa", "xhosa", "Xhosa-Sprache", "XHO"),
    YAO("YAO", "yao", "Yao-Sprache (Bantusprache)", null, "YAO"),
    YAO_1("YAO", "yao", "Yao-Sprache (Bantusprache)", null, "YAO"),
    YAP("YAP", "yapois", "Yapesisch", "Jiddisch", "YAPESE"),
    YAPESE("YAPESE", "yapois", "Yapesisch", "Jiddisch", "YAP"),
    YID("YID", "Yiddish", "yiddish", "Jiddisch", "YI"),
    YI("YI", "Yiddish", "yiddish", "Jiddisch", "YID"),
    YOR("YOR", "Yoruba", "yoruba", "Yoruba-Sprache", "YO"),
    YO("YO", "Yoruba", "yoruba", "Yoruba-Sprache", "YOR"),
    YPK("YPK", "Yupik languages", "yupik, langues", "Ypik-Sprachen", "ZAPOTEC"),
    ZAP("ZAP", "zapot\u00e8que", "Zapotekisch", "Bliss-Symbol", "ZAPOTEC"),
    ZAPOTEC("ZAPOTEC", "zapot\u00e8que", "Zapotekisch", "Bliss-Symbol", "ZAP"),
    ZBL("ZBL", "Blissymbols; Blissymbolics; Bliss", "symboles Bliss; Bliss", "Bliss-Symbol", "ZENAGA"),
    ZEN("ZEN", "zenaga", "Zenaga", null, "ZENAGA"),
    ZENAGA("ZENAGA", "zenaga", "Zenaga", null, "ZEN"),
    ZGH("ZGH", "Standard Moroccan Tamazight", "amazighe standard marocain", "Zhuang", "ZA"),
    ZHA("ZHA", "Zhuang; Chuang", "zhuang; chuang", "Zhuang", "ZA"),
    ZA("ZA", "Zhuang; Chuang", "zhuang; chuang", "Zhuang", "ZHA"),
    CHI_1("CHI", "Chinese", "chinois", "Chinesisch", "ZH"),
    ZHO_1("ZHO", "Chinese", "chinois", "Chinesisch", "ZH"),
    ZH_1("ZH", "Chinese", "chinois", "Chinesisch", "ZHO"),
    ZND("ZND", "Zande languages", "zand\u00e9, langues", "Zande-Sprachen", "ZU"),
    ZUL("ZUL", "Zulu", "zoulou", "Zulu-Sprache", "ZU"),
    ZU("ZU", "Zulu", "zoulou", "Zulu-Sprache", "ZUL"),
    ZUN("ZUN", "zuni", "Zu\u00f1i-Sprache", "Kein linguistischer Inhalt", "ZUNI"),
    ZUNI("ZUNI", "zuni", "Zu\u00f1i-Sprache", "Kein linguistischer Inhalt", "ZUN"),
    ZXX("ZXX", "No linguistic content; Not applicable", "pas de contenu linguistique; non applicable", "Kein linguistischer Inhalt", null),
    ZZA("ZZA", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", "zaza; dimili; dimli; kirdki; kirmanjki; zazaki", "Zazaki", null);
    private final String m_sID;
    private final String m_sDisplayName;
    private final String m_sFrench;
    private final String m_sGerman;
    private final String m_sRef;

    private ELanguageCode22(
        @Nonnull
        @Nonempty
        final String sID,
        @Nonnull
        final String sDisplayName,
        @Nullable
        final String sFrench,
        @Nullable
        final String sGerman,
        @Nullable
        final String sRef) {
        m_sID = sID;
        m_sDisplayName = sDisplayName;
        m_sFrench = sFrench;
        m_sGerman = sGerman;
        m_sRef = sRef;
    }

    @Nonnull
    @Nonempty
    public String getID() {
        return m_sID;
    }

    @Nonnull
    public String getDisplayName() {
        return m_sDisplayName;
    }

    @Nullable
    public String getFrench() {
        return m_sFrench;
    }

    @Nullable
    public String getGerman() {
        return m_sGerman;
    }

    @Nullable
    public String getRef() {
        return m_sRef;
    }

    @Nullable
    public static ELanguageCode22 getFromIDOrNull(
        @Nullable
        final String sID) {
        return EnumHelper.getFromIDOrNull(ELanguageCode22 .class, sID);
    }

    @Nullable
    public static String getDisplayNameFromIDOrNull(
        @Nullable
        final String sID) {
        final ELanguageCode22 eValue = ELanguageCode22 .getFromIDOrNull(sID);
        return ((eValue == null)?null:eValue.getDisplayName());
    }
}
